chef/chef-dk

lib/chef-dk/command/generator_commands/app.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/command/generator_commands/cookbook_code_file.rb
lib/chef-dk/skeletons/code_generator/files/default/converge_spec.rb
lib/chef-dk/skeletons/code_generator/files/default/spec_helper.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/recipe.rb
lib/chef-dk/skeletons/code_generator/templates/default/default_recipe.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb
spec/shared/a_file_generator.rb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/recipe_spec.rb

Any recipe generated by `chef generate` should now also automatically have a corresponding spec file template generated in spec/unit/recipes. In addition, a spec/spec_helper.rb file will be created if one does not currently exist.
I also consolidated the redundant template/recipe.rb and template/default_recipe.rb files for easier maintenance.

Add chefspec to generators

---

chef-dk.gemspec
lib/chef-dk/configurable.rb
lib/chef-dk/policyfile/uploader.rb
lib/chef-dk/policyfile_services/push.rb
spec/unit/policyfile/uploader_spec.rb
spec/unit/policyfile_services/push_spec.rb

* Add support for uploading policies to the "native" API rather than as data bag items
* Usage of the native API is configured with `policy_document_native_api true` in `~/.chef/config.rb` (or `knife.rb`). Defaults to false (for now).
* Also updated Chef dependency to `~> 12.0` now that Chef 12.0 is released.
* Tested against Chef Zero w/ https://github.com/opscode/chef-zero/pull/111 (also needed some local modifications to `chef` to make Chef FS happy).
* Chef patch (which is needed to make the feature work end-to-end) is forthcoming.
@chef/client-engineers @chef/delivery

Policyfile Native API support for `chef push`

---

lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Previously the serverspec spec_helper.rb file was located in the same directory as the default_spec.rb, and while this worked it also made it impossible to write helper functions that were usable across multiple test suites.
The new location will allow for this behavior.

Change location of serverspec spec_helper.rb file

---

lib/chef-dk/policyfile/uploader.rb

We don't have a clear upgrade path on the server side for folks using
the preview versions of the new policyfile APIs; it's likely that some
data, such as policyfile lock documents, will be missing fields that we
expect to be required in the final version of the API. Therefore it's
unlikely that we'll provide an upgrade mechanism for these documents,
and instead will probably just delete them if a user has any data
created with a preview version of the API. This warning makes that risk
clear for anyone trying the feature.
@sdelano @chef/client-engineers

Use stronger language when warning about native API.

---

lib/chef-dk/policyfile/uploader.rb
spec/unit/policyfile/uploader_spec.rb

When `policy_document_native_api` is `true`, upload cookbooks to the new `cookbook_artifacts` API. Also reorganizes the tests to better separate common and divergent behavior for compatibility vs. native modes.
@chef/client-engineers @chef/delivery

Upload to Cookbook Artifacts API when Native Mode is Enabled

---

CONTRIBUTING.md

Updates the CLA links to use supermarket. One thing to consider is, [on the supermarket guide for signing the CLA](https://supermarket.chef.io/become-a-contributor), it tells corporate contributors to check if they should be on an existing CLA before going to the CCLA signup. Worth adding any verbiage about that?

Point to supermarket for CLA links

---

lib/chef-dk/policyfile_lock.rb
spec/unit/policyfile_lock_build_spec.rb

Adds `revision_id` to Policyfile lock documents. This gives us the following benefits:
* Users can talk about the differences between revisions more easily, e.g., "in 123abc the run list is like this but in 456def it's like that."
* Provides a natural primary key that we can use in HTTP API URLs, e.g., you could GET a policyfile lock document via `GET /policies/:policy_name/revisions/:revision_id`, as specified in https://github.com/chef/chef-rfc/pull/91
Note that the revision ID is computed by creating a string containing the run list, named run lists, and cookbook identifiers and taking a SHA-1 of that. This means that non-functional updates to a policyfile lock (e.g., change the source of a cookbook but don't change the code) don't result in a new revision id, which means a user could …

Policyfile Revision IDs

---

lib/chef-dk/command/verify.rb

This is the Chef-DK component of https://github.com/chef/chef/pull/3039 - the tests I modified in that PR will continue to run for regular chef builds, but will be ignored when running `chef verify`.  This will exclude them from the nightly builds in CI which have been failing.
\cc @chef/client-core

Excluding failing tests from nightlies

---

CHANGELOG.md
chef-dk.gemspec
lib/chef-dk/policyfile/read_cookbook_for_compat_mode_upload.rb
lib/chef-dk/policyfile/uploader.rb
spec/spec_helper.rb
spec/unit/policyfile/uploader_spec.rb

Updates ChefDK to interop correctly with Erchef's cookbook artifacts endpoint. Also updates expected Policyfile upload URL to match erchef (and the relevant RFC).

Erchef Policyfile integration

---

lib/chef-dk/policyfile/cookbook_location_specification.rb
spec/spec_helper.rb
spec/unit/policyfile_evaluation_spec.rb

Make just `cookbook "foo"` work correctly in a `Policyfile.rb`.

Empty Cookbook Options Fix

---

lib/kitchen/provisioner/policyfile_zero.rb

**EDIT** This is ready for merge now that TK 1.4 is in master.  TK 1.4 and this will be used in the latest omnibus build of chef-dk.
\cc @danielsdeleo

Updating to use new shells available to windows-guest-branch of test-kitchen

---

CHANGELOG.md
lib/chef-dk/cli.rb
lib/chef-dk/version.rb
lib/kitchen/provisioner/policyfile_zero.rb

\cc @danielsdeleo @jdmundrawala @chef/client-core

ChefDK 0.5.0.rc.1 Release

---

README.md

Fixes the main link to point at the downloads page instead of at corpsite.

Changes link to point to downloads.chef.io

---

spec/spec_helper.rb
spec/unit/command/verify_spec.rb

\cc @chef/client-core 
I'm not sure why this fails - but it only does it sometimes and I think I have only seen it happen on debian.

Disabling test that fails intermitently on debian

---

lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/policyfile_compiler.rb
lib/chef-dk/policyfile_lock.rb
spec/unit/policyfile_evaluation_spec.rb
spec/unit/policyfile_lock_build_spec.rb

Implements ChefDK side of adding attributes to policyfiles. For now they will be ignored in Chef Client. Chef Server should preserve them unmodified but not do any checking of the content, though I have not verified this yet. Attributes are included in the revision id computation, using an incomplete implementation of [Canonical JSON](http://wiki.laptop.org/go/Canonical_JSON). Most common user inputs should work fine with the implementation that is there now, though we'll have to make it more solid when we (very eventually) enable server-side verification of the revision id.
Also switched the revision id logic to use SHA2-256, since eventually we want the revision id to ensure data integrity.

Policyfile attributes

---

lib/chef-dk/policyfile_lock.rb
spec/unit/policyfile_lock_serialization_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb
spec/unit/policyfile_services/push_spec.rb

This fixes an issue where ChefDK would check your locks to see if any local cookbooks were updated between `chef install` and `chef push` and rewrite your lockfile with the attributes removed.

Ensure attributes are maintained in deserialization

---

lib/chef-dk/command/update.rb
lib/chef-dk/policyfile_services/update_attributes.rb
lib/chef-dk/service_exceptions.rb
spec/unit/command/update_spec.rb
spec/unit/policyfile_services/update_attributes_spec.rb

Enables users to update only the attributes of their policyfile.lock by running `chef update -a`.

Attribute only update

---

chef-dk.gemspec
lib/chef-dk/policyfile/differ.rb
lib/chef-dk/ui.rb
spec/test_helpers.rb
spec/unit/policyfile/differ_spec.rb

Add class that can diff policyfile lock documents on a piecemeal basis and produce an itemized diff. This should make it more user friendly than a straight-up diff of the JSON, since items are diffed in small pieces with headings for context.
Not wired up to any CLI interface yet, that will be next. I have some ideas on what exactly the features of that might be, see here: https://gist.github.com/danielsdeleo/61b32c307a309269b253

Add Policy Differ Class

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/diff.rb
lib/chef-dk/command/push.rb
lib/chef-dk/pager.rb
lib/chef-dk/policyfile/comparison_base.rb
lib/chef-dk/policyfile/differ.rb
lib/chef-dk/service_exceptions.rb
spec/spec_helper.rb
spec/unit/command/diff_spec.rb
spec/unit/pager_spec.rb
spec/unit/policyfile/comparison_base_spec.rb

Adds a `chef diff` command that can diff the current policyfile lock on disk with git commits or locks on the server, or diff two git commits or two revisions on the server. Output is sent to the PAGER by default, and if it's `less`, it's run with colors and such enabled, similar to how git does it.

CLI front-end for diff

---

CHANGELOG.md
lib/chef-dk/policyfile/chef_repo_cookbook_source.rb
lib/chef-dk/policyfile/cookbook_sources.rb
lib/chef-dk/policyfile/dsl.rb
spec/unit/fixtures/local_path_cookbooks/cookbook-with-a-dep/Berksfile
spec/unit/fixtures/local_path_cookbooks/cookbook-with-a-dep/README.md
spec/unit/fixtures/local_path_cookbooks/cookbook-with-a-dep/chefignore
spec/unit/fixtures/local_path_cookbooks/cookbook-with-a-dep/metadata.rb
spec/unit/fixtures/local_path_cookbooks/cookbook-with-a-dep/recipes/default.rb
spec/unit/policyfile/chef_repo_cookbook_source_spec.rb
spec/unit/policyfile_evaluation_spec.rb

allows pulling the universe to depsolve from a local monolithic chef_repo path.

add chef_repo cookbook source

---

spec/unit/policyfile/comparison_base_spec.rb

In Ci the file is still readable after setting 000 permissions, so we're
not testing with the proper context.
@tyler-ball

Use a stub to ensure we always test file-not-readable behavior

---

lib/chef-dk/configurable.rb
lib/chef-dk/policyfile/uploader.rb

Next Chef Server release (probably 12.0.9) will have policyfile APIs
enabled by default, and it's safer for users if we default to the native
APIs. Also, we don't plan on any compat-breaking data changes in the
foreseeable future, so the warning is no longer relevant.
@chef/lob

Enable policyfile native mode by default, remove warning

---

CHANGELOG.md
lib/chef-dk/version.rb

This contains the following fixes (so far):
* #368 - undefiend_method error when using `chef diff`
* Updates chef client to 12.3.0, which fixes OSX converges (uses homebrew instead of macports)

Preparing the ChefDK 0.5.1 release

---

lib/chef-dk/skeletons/code_generator/files/default/Berksfile
lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/serverspec_default_spec.rb.erb

Fixes https://github.com/chef/chef-dk/issues/380
- Adds a rubocop.yml that ignores the single space before arguments in
metadata.rb
- Fix quoting in Berksfile
- Clean up horribly offensive additional newlines, and trailing
whitespace in generated specs :)

Fixes #380, resolve generated cookbook rubocops

---

PROVISION_README.md
chef-dk.gemspec
lib/chef-dk/builtin_commands.rb
lib/chef-dk/chef_runner.rb
lib/chef-dk/command/provision.rb
lib/chef-dk/exceptions.rb
lib/chef-dk/service_exceptions.rb
spec/unit/chef_runner_spec.rb
spec/unit/command/provision_spec.rb

Adds a `chef provision` command to ChefDK. I created this because, when I was working on a Policyfile "walkthrough" blog post, I had no good way to provision production-y machines (which I needed to properly demonstrate how cookbook "versioning" works in Policyfiles). I mostly like how Chef Provisioning works but I wanted some command line integration for convenience.
For now, I'm considering this an experimental feature. It covers my use cases but I'm only scratching the surface of what you can do with Chef Provisioning, so it's possible that some design decision I made will not produce a good user experience for many cases, therefore I want to explicitly reserve the right to make radically breaking changes for a little while. Once this is shipped I'll solicit feedback and we'll see how …

Provision command

---

lib/chef-dk/cookbook_profiler/git.rb
spec/unit/cookbook_profiler/git_spec.rb

As described in #364 when you create a repo (`git init`) but don't have a commit, you're on an unborn master branch. Commands such as `git rev-parse HEAD` will fail in such a scenario, which causes most Policyfile commands to fail (when attempting to extract git information about the cookbook). There does not seem to be a canonical way to detect that you're on an unborn branch, git uses the same exit code for all failures, and the error messages printed to stderr do not seem to be stable across git versions. So I settled on feeding the output of `git symbolic-ref -q HEAD` to `show-ref --verify $SYMBOLIC_REF` (we expect the first command to succeed and the second command to fail on an unborn branch).
fixes #364 
@chef/client-core @tyler-ball

Don't error when profiling an unborn branch

---

chef-dk.gemspec

Later versions of chef-provisioning will depend on winrm 1.3, which conflicts with knife-windows (0.8.4 depends on winrm 1.2) when bundled in the ChefDK.  We can include chef-provisioning 1.2 when knife-windows 1.0 is released because both of those will depend on winrm 1.3
\cc @chef/client-maintainers

Pinning chef-provisioning to 1.1.1

---

lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

These changes are in service of https://github.com/chef/omnibus-chef/pull/394.
/cc @chef/ociv @chef/delivery @chef/client-core @fnichol @tyler-ball @cwebberOps @adamhjk

Add basic smoke tests for the Delivery CLI

---

PROVISION_README.md
lib/chef-dk/command/provision.rb
spec/unit/command/provision_spec.rb

* Add a `-t TARGET` option. This is intended to be used when bootstrapping/converging existing machines via the SSH driver
* Add a `--opt OPT=VALUE` option. This lets users set any arbitrary option they want that we haven't anticipated (or is specific to their org, use case, etc.).

Provision target host option and arbitrary options

---

lib/chef-dk/command/show_policy.rb
spec/unit/command/show_policy_spec.rb

The requisite APIs for this don't exist yet so it is not yet usable (and
therefore not added to the command lookup). The work done so far
provides a UI so we know what kind of data the API must provide when
implemented.
Because of the above, I've avoided adding too much unit testing for some of the "lower level" functionality, because it may change when it uses the API for real. The functionality is generally pretty well exercised by the tests for the command though.

Add `chef show-policy` command

---

lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

This reverts commit a1342cb7a7f15b6ec292655897de28857ee00ccc, reversing
changes made to b32613a8a2bdd49e33abbab6e4a236afba217238.
Not quite ready to ship the delivery CLI in ChefDK... soon, but not right now.
See also: https://github.com/chef/omnibus-chef/pull/404

Revert "Merge pull request #398 from chef/schisamo/delivery-cli"

---

lib/chef-dk/command/verify.rb

/cc @jdmundrawala @fnichol @danielsdeleo 
This may be the wrong way to do this.  Basically, I'm trying to perform an SSL check _only_ if we can actually connect to the host.  This is to prevent failing `chef verify` on a location where everything is locked down by firewall.
The other option is to add some kind of flag like `--build-verify` that we only pass to our CI stage.
What do yall think?

Adding verification for openssl issue, fixes https://github.com/chef/chef-dk/issues/420

---

lib/chef-dk/cookbook_omnifetch.rb
lib/chef-dk/helpers.rb
spec/unit/helpers_spec.rb

Related omnibus changes: https://github.com/chef/omnibus-chef/pull/406

Allow setting CHEFDK_HOME

---

lib/chef-dk/command/show_policy.rb
lib/chef-dk/policyfile_services/show_policy.rb
spec/unit/command/show_policy_spec.rb
spec/unit/policyfile_services/show_policy_spec.rb

Adds the ability to display a specific policyfile lock revision by giving the policy name and group. This is displayed via the pager by default.

Show specific policy

---

spec/unit/command/exec_spec.rb

RSpec now emits these warnings: 
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`.
```
Fixed in this commit.

Fix RSpec warnings for "potential false positives"

---

chef-dk.gemspec
lib/chef-dk/command/export.rb
lib/chef-dk/policyfile_services/export_repo.rb
spec/unit/command/export_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb

Adds a flag to `chef export` so you can export a tarball instead of just the plain directory structure. This is to support a future `chef push-archive` command that can be used to transfer policyfiles and the relevant code to an environment with limited networking access.

Export archive

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/push_archive.rb
lib/chef-dk/policyfile/cookbook_locks.rb
lib/chef-dk/policyfile_lock.rb
lib/chef-dk/policyfile_services/export_repo.rb
lib/chef-dk/policyfile_services/push_archive.rb
lib/chef-dk/service_exceptions.rb
spec/unit/command/push_archive_spec.rb
spec/unit/policyfile/cookbook_locks_spec.rb
spec/unit/policyfile_lock_serialization_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb
spec/unit/policyfile_services/push_archive_spec.rb

Add a `chef push-archive` command that can upload a policy archive (tarball) directly to the server. So you can do:
```bash
chef export -a .
chef push-archive prodution aar-d81e80ae9bb9778e8c4b7652d29b11d2111e763a840d0cadb34b46a8b2ca4347.tgz
```

Push Archive Command

---

chef-dk.gemspec

This is a workaround for https://github.com/ffi/ffi/pull/441

Pin FFI to 1.9.8 because 1.9.9 breaks on windows

---

chef-dk.gemspec

This reverts commit d5f1bd6b016351466223154bc5406ca0e3479fca.

Revert "Pin FFI to 1.9.8 because 1.9.9 breaks on windows"

---

lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/chef_repo_cookbook_source.rb
lib/chef-dk/policyfile/chef_server_cookbook_source.rb
lib/chef-dk/policyfile/community_cookbook_source.rb
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/policyfile/null_cookbook_source.rb
lib/chef-dk/policyfile_compiler.rb
spec/unit/policyfile_demands_spec.rb
spec/unit/policyfile_evaluation_spec.rb

Addresses https://github.com/chef/chef-dk/issues/430
This allows you to have multiple `default_source` lines in your policyfile.rb, so you can have a `chef_repo` with all your org-specific stuff, but pull cookbooks from the public supermarket easily. The way it's designed right now, the cookbook sets need to be disjoint (i.e., there cannot be cookbooks with the same name in both locations). If you manually specify a cookbook's source with a `cookbook "foo", source_option: "place"` line, though it will be respected. One downside of that is, if there is a conflict between your two sources, and the cookbook is totally irrelevant (wouldn't be in the dependency solution), it'll end up in your policy anyway, because adding the `cookbook` line tells chef-dk you want that cookbook around. That …

Multiple policyfile sources

---

CHANGELOG.md
lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

Check that every shipped version of `chef-provisioning` can load a version of all of the shipped drivers.

Add `chef verify chef-provisioning`

---

lib/chef-dk/policyfile_services/clean_policies.rb
lib/chef-dk/service_exceptions.rb
spec/unit/policyfile_services/clean_policies_spec.rb
spec/unit/policyfile_services/show_policy_spec.rb

Adds a service object that garbage collects unused policyfile revision objects on the server. This requires APIs that don't yet exist, so it only works with the HTTP code mocked out. Implementing the server API is the next step, then I'll come back and add a command to the CLI that exposes this to the end user.

Mockup policyfile revision cleanup

---

lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/undo_record.rb
lib/chef-dk/policyfile/undo_stack.rb
lib/chef-dk/policyfile_services/rm_policy_group.rb
lib/chef-dk/service_exceptions.rb
spec/unit/policyfile/undo_record_spec.rb
spec/unit/policyfile/undo_stack_spec.rb
spec/unit/policyfile_services/rm_policy_group_spec.rb

Relies on APIs that don't exist yet, so it won't actually work. That will be addressed soon, then I'll come back and add CLIs on top of this.
Also adds an undo stack so that we don't need to have a naggy confirmation dialog thing

Backend for policy group removal

---

lib/chef-dk/policyfile_services/clean_policy_cookbooks.rb
lib/chef-dk/service_exceptions.rb
spec/unit/policyfile_services/clean_policy_cookbooks_spec.rb

This relies on some APIs that don't exist yet, so it cannot work until those are created.
Adds a service object that traverses policies and cookbook artifacts to determine which cookbook artifacts are no longer referenced by any policy revision, then deletes those.
It has to fetch every policy revision from the server, and also must make a delete call for each unreferenced cookbook. This is probably pretty slow in a larger organization, but I think this is okay for now because it's a periodic maintenance command, not something you'd run frequently. It also will probably be faster if you cleanup policy revisions first, which I will note in the documentation.

Add service class to GC cookbook_artifacts

---

lib/chef-dk/command/base.rb
lib/chef-dk/command/generate.rb
spec/unit/command/base_spec.rb
spec/unit/command/generate_spec.rb

Adds error handling for the case where a CLI option requires an argument but none is given. For example, the `-c` option requires an argument (path to a config file), so a command like `chef show-policy -c` is not valid. Currently, this error bubbles up for most commands so you get output like this:
```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options': missing argument: -c (OptionParser::MissingArgument)
from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/command/show_policy.rb:136:in `apply_params!'
from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/command/show_policy.rb:90:in `run'
from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/command/base.rb:57:in `run_with_default_options'
from …
```

Catch bad params

---

lib/chef-dk/command/export.rb
lib/chef-dk/command/generator_commands/app.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/command/generator_commands/policyfile.rb
lib/chef-dk/command/generator_commands/repo.rb
lib/chef-dk/command/install.rb
lib/chef-dk/command/update.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/policyfile_spec.rb

I noticed that we were only displaying the banner and not the options when commands are given too many or not enough arguments. This fixes all instances I could find with `git grep` where this happened. Also standardizes on displaying this output on stderr.

Show full usage when given invalid args

---

lib/chef-dk/command/shell_init.rb
lib/chef-dk/completions/zsh.zsh.erb
spec/unit/command/shell_init_spec.rb

Adds very simple completion of subcommand names for zsh with subcommand descriptions. For example, typing `chef` and hitting <TAB> will show the following:
```
ddeleo@lorentz chef-dk git:(complete-zsh)> chef
diff          -- Generate an itemized diff of two Policyfile lock documents
env           -- Prints environment variables used by ChefDK
exec          -- Runs the command in context of the embedded ruby
export        -- Export a policy lock as a Chef Zero code repo
gem           -- Runs the `gem` command in context of the embedded ruby
generate      -- Generate a new app, cookbook, or component
install       -- Install cookbooks from a Policyfile and generate a locked cookbook set
provision     -- Provision VMs and clusters via cookbook
push          -- Push a local policy lock to a …
```

Add basic zsh completion for chef command

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/delete_policy_group.rb
lib/chef-dk/command/undelete.rb
lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/undo_record.rb
lib/chef-dk/policyfile/undo_stack.rb
lib/chef-dk/policyfile_services/rm_policy_group.rb
lib/chef-dk/policyfile_services/undelete.rb
lib/chef-dk/service_exceptions.rb
spec/unit/command/undelete_spec.rb
spec/unit/policyfile/undo_record_spec.rb
spec/unit/policyfile/undo_stack_spec.rb
spec/unit/policyfile_services/rm_policy_group_spec.rb
spec/unit/policyfile_services/undelete_spec.rb

Adds the `chef undelete` subcommand. This reads undo records created by `chef delete-policy-group` (and `chef delete-policy` in the future) and loads the backup data back on to the Chef Server. It works in one of 3 ways:
* `chef undelete` lists the undo operations available.
* `chef undelete --last` undoes the last delete operation you did
* `chef undelete --id ID` undoes a specific delete operation (you can get the ID from the list).

`chef undelete` command

---

lib/chef-dk/command/install.rb
lib/chef-dk/policyfile/community_cookbook_source.rb
spec/unit/command/install_spec.rb

Makes `chef install` load config.rb/knife.rb, so SSL settings will get picked up and `trusted_certs_dir` will be set correctly.
@jtimberman Can you try this out?

Chef install configuration

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/clean_policy_revisions.rb
lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile_services/clean_policies.rb
spec/unit/command/clean_policy_revisions_spec.rb

Adds a subcommand to delete unused policy revisions, and fixes some minor issues with the service class discovered in manual integration testing.

`chef clean-policy-revisions` command

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/clean_policy_cookbooks.rb
lib/chef-dk/policyfile_services/clean_policy_cookbooks.rb
spec/unit/command/clean_policy_cookbooks_spec.rb
spec/unit/policyfile_services/clean_policy_cookbooks_spec.rb

CLI front-end for the `clean_policy_cookbooks` service object. Enumerates all policy revisions and cookbooks, then deletes cookbooks that aren't referenced by any policy revision.

Add `chef clean-policy-cookbooks` subcommand

---

chef-dk.gemspec

Per @jaym this triggers a bug in rubygems if a newer RC is available.

Remove mixlib-shellout RC from gemspec

---

lib/chef-dk/policyfile/lister.rb
lib/chef-dk/policyfile_services/show_policy.rb
spec/unit/policyfile_services/show_policy_spec.rb

Fixes a bug where showing a policy that doesn't exist would show that
policy as not being applied to any groups (but not indicating that it
doesn't exist), like this:
```
prompt$ chef show-policy nope-nope-nope -c ~/.chef/localserver.rb
nope-nope-nope
==============
* dev:         *NOT APPLIED*
* example:     *NOT APPLIED*
* production:  *NOT APPLIED*
* staging:     *NOT APPLIED*
```
Now the output is like:
```
nope-nope-nope
==============
No policies named 'nope-nope-nope' are associated with a policy group
```

Always show 'no policy' message when policy doesn't exist

---

CHANGELOG.md

Instead of entries like Last Release or Unreleased,
we always refer to the version we would like changes to
go out in so that we can tag a nightly whenever we need to
and have the CHANGELOG say the right thing.

Update Changelog version numbers

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/delete_policy.rb
lib/chef-dk/policyfile_services/rm_policy.rb
lib/chef-dk/policyfile_services/undelete.rb
lib/chef-dk/service_exceptions.rb
spec/unit/command/delete_policy_group_spec.rb
spec/unit/command/delete_policy_spec.rb
spec/unit/policyfile_services/rm_policy_spec.rb
spec/unit/policyfile_services/undelete_spec.rb

Adds `chef delete-policy POLICY_NAME` subcommand. Like `chef delete-policy-group`, this provides undo via `chef undelete`. I've tested both delete and undelete manually against a Chef Server nightly (12.2 will be the actual release with the required APIs).

Add `chef delete-policy` subcommand

---

lib/chef-dk/command/shell_init.rb
spec/unit/command/shell_init_spec.rb

PowerShell fails with an error when doing "chef shell-init powershell | iex".
This is because iex does not like an empty line in an expression.
This is a regression from Chef DK 0.7
cc @danielsdeleo @chef/client-maintainers

PowerShell does not like empty line in shell-init

---

lib/chef-dk/command/verify.rb
lib/chef-dk/helpers.rb
spec/unit/helpers_spec.rb

Since we have move our symlinks from `/usr/bin` to `/usr/local/bin` on Mac OS X currently smoke tests of `"package installation"` component are failing.

Run commands from /usr/local/bin on Mac during 'package installation' smoke tests

---

lib/chef-dk/command/clean_policy_cookbooks.rb
lib/chef-dk/command/clean_policy_revisions.rb
lib/chef-dk/command/delete_policy.rb
lib/chef-dk/command/delete_policy_group.rb
lib/chef-dk/command/export.rb
lib/chef-dk/command/install.rb
lib/chef-dk/command/provision.rb
lib/chef-dk/command/push.rb
lib/chef-dk/command/show_policy.rb
lib/chef-dk/command/undelete.rb
lib/chef-dk/command/update.rb

We can stay pre-1.0 while we finish completing the feature set, but things are solid enough we don't need to bang everyone over the head with warnings any more.

remove beta warnings from policyfile commands

---

lib/chef-dk/policyfile_lock.rb
spec/unit/policyfile_lock_serialization_spec.rb

This fixes a bug where running `chef push` removes named_run_lists from the lockfile. This was happening because ChefDK slurps the lockfile and updates the identifiers for any path-sourced cookbooks when you run `chef push` (that behavior exists to enable faster feedback cycles). Without the patch, the named run lists weren't getting set on the slurped lockfile object, so when the lockfile was written back to disk, the named_run_lists were removed.

Include named_run_lists when deserializing a lockfile

---

lib/chef-dk/command/export.rb
lib/chef-dk/policyfile_services/export_repo.rb
spec/unit/policyfile_services/export_repo_spec.rb

This removes a manual step when running exported policy. Now you can just use the included config file, like:
```
chef export /tmp/my-policy
cd /tmp/my-policy
chef-client -c client.rb -z
```

Include a valid config in exported policies

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/command/generator_commands/policyfile.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/Policyfile.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

* Update Policyfile template so it can be setup to work out of the box
* Comment-out berksfile generation in the cookbook generator recipe (this allows end users to generate a generator and uncomment the berksfile part if they want)
* Generate a Policyfile.rb in the cookbook generator
* Use the policyfile provisioner in the generated kitchen YAML.

Generate Policyfiles instead of Berksfiles in new cookbooks

---

lib/chef-dk/chef_runner.rb
lib/chef-dk/skeletons/code_generator/files/default/spec_helper_policyfile.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/spec_helper.rb

With this change, `chef generate cookbook foo; cd foo; chef install; rspec` works out of the box.
I also found and fixed deprecated chef library usage.

Make Generated Cookbook Use ChefSpec Policyfile Mode

---

chef-dk.gemspec

Add gemspec files to allow bundler to run from the gem

---

chef-dk.gemspec
lib/chef-dk/policyfile/cookbook_location_specification.rb
spec/unit/policyfile/cookbook_location_specification_spec.rb

Fixes https://github.com/chef/chef-dk/issues/564 and a similar bug I discovered in testing.
Error messages now look like:
```
Building policy example-application-service
Expanded run list: recipe[apt::default]
Caching Cookbooks...
Installing foo >= 0.0.0 from path
Error: Failed to generate Policyfile.lock
Reason: (CookbookOmnifetch::NotACookbook) The resource at '/Users/ddeleo/oc/chef-dk/no/such/dir/foo' does not appear to be a valid cookbook. Does it have a metadata.rb?
```

Better "not a cookbook" errors

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/command/generator_commands/policyfile.rb
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/dot-chef-repo.txt
lib/chef-dk/skeletons/code_generator/files/default/repo/policies/README.md
lib/chef-dk/skeletons/code_generator/recipes/repo.rb
lib/chef-dk/skeletons/code_generator/templates/default/Policyfile.rb.erb
spec/unit/command/generator_commands/policyfile_spec.rb
spec/unit/command/generator_commands/repo_spec.rb
spec/unit/policyfile_demands_spec.rb
spec/unit/policyfile_evaluation_spec.rb

* Replace roles/ and environments/ directories with a policies/ directory (also add a comment for how to reverse this if using the code in a custom generator).
* Add a `.chef-repo.txt` file at the root of generated Chef Repos to allow chef-dk to adjust generator behavior for chef repos
* Use given arguments to `chef generate policyfile` to set the policy name and run list; add a `chef_repo` source to generated policies when generating a policy in a chef repo.

Make chef repo prefer policyfiles

---

lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

Originally I was planning to do a bigger refactor of `chef verify` to pull out the helper code and separate each component into its own file, but I want to avoid a messy merge with https://github.com/chef/chef-dk/pull/562
This just checks that cookbooks produced by `chef generate cookbook` will pass the generated chefspec tests. I was able to make it fail by temporarily changing the generator to put bad code in the spec_helper.rb

Verify that generated cookbooks pass chefspec

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/command/generator_commands/repo.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/attributes/default.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/recipes/default.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/data_bags/README.md
lib/chef-dk/skeletons/code_generator/files/default/repo/roles/README.md
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/repo.rb
lib/kitchen/provisioner/policyfile_zero.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/repo_spec.rb

cf. https://chefio.atlassian.net/browse/FLOW-82
Makes berks/policyfile configurable with a CLI option and flips the default back to berks. Additionally addressed some minor issues related to generators.
@chef/workflow

Configurable depsolver

---

POLICYFILE_README.md
lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/chef_repo_cookbook_source.rb
lib/chef-dk/policyfile/community_cookbook_source.rb
lib/chef-dk/policyfile/delivery_supermarket_source.rb
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/policyfile_compiler.rb
spec/unit/policyfile/chef_repo_cookbook_source_spec.rb
spec/unit/policyfile/community_cookbook_source_spec.rb
spec/unit/policyfile/delivery_supermarket_source_spec.rb
spec/unit/policyfile_demands_spec.rb
spec/unit/policyfile_evaluation_spec.rb

Implements a DSL syntax to specify that a given source is the preferred one for a given cookbook. It looks like this:
```ruby
default_source :supermarket
default_source :supermarket, "https://my.supermarket.example" do |s|
s.preferred_source_for "chef-client"
end
```
Still todo:

Preferred supermarkets for cookbooks

---

lib/chef-dk/policyfile_compiler.rb
spec/unit/policyfile_demands_spec.rb

When running `chef install` and there are two cookbook sources that have
a cookbook of the same name, there would be an implicit nil return when
filtering that cookbook from the graph, which would lead to:
```
Error: Failed to generate Policyfile.lock
Reason: (NoMethodError) undefined method `each' for nil:NilClass
```
...when generating the Solve::Graph. Returning an empty Hash causes the
coobkook to be omitted from the Solve::Graph, which is what we want.
@chef/workflow

Return correct type when filtering out cookbooks from graph

---

lib/chef-dk/exceptions.rb
spec/unit/policyfile_demands_spec.rb

The current suggested code has bad syntax and uses an incorrect method name.
@chef/workflow

Fix incorrect suggested code in errors

---

lib/chef-dk/policyfile_services/export_repo.rb
spec/unit/policyfile_services/export_repo_spec.rb

Makes `chef export` respect the `chefignore` file. Frequently very large files like a VM image are stored in a cookbook's ignored directories, which can be bad when trying to copy cookbooks into a VM for testing.
Fixes https://github.com/chef/chef-dk/issues/519
@tbunnyman I pulled in your commit and cleaned it up a little. It turns out there is already a chefignored file in the fixture data, so the existing tests only needed to be modified a little bit to handle the new behavior.
cc @chef/workflow

'chef export' respects chefignore

---

chef-dk.gemspec
lib/chef-dk/chef_runner.rb

`Chef::PolicyBuilder::Dynamic` was added in Chef 12.5, so that is now our minimum version. I also added an explicit require for it, though it should get brought in from `require 'chef'`

Update chef dependency to ~> 12.5

---

lib/chef-dk/command/update.rb
spec/unit/command/update_spec.rb

Similar to `chef install`, `chef update` does not have any direct
configurables, but may rely on configuration being loaded in order to
configure SSL to correctly verify connections to a private supermarket.
@chef/workflow

Load configuration when running `chef update`

---

POLICYFILE_README.md
lib/kitchen/provisioner/policyfile_zero.rb

Note that kitchen does a little bit of magic to distribute per-suite
configuration to the right place, so to use this to customize suites,
you have to explicitly name it as a provisioner customization, like:
```
suites:
- name: default
attributes:
- name: other
provisioner:
named_run_list: example
```
It'd be nice to clean that up when we move policyfile support into kitchen proper. (See: https://github.com/test-kitchen/test-kitchen/blob/9b906c6292d9c183ffb5d631f7355c030790f058/lib/kitchen/data_munger.rb#L625-L688)
@chef/workflow

Add named_run_list support to provisioner

---

lib/chef-dk/policyfile_services/install.rb
spec/unit/policyfile_services/install_spec.rb

When I was working with delivery I wanted to be able to access this information in build logs. It's easy to get when you're doing things on your laptop but that's inconvenient when things are happening on some random Ci machine.
@chef/workflow

Show revision id when running `chef install`

---

lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/cookbook_location_specification.rb
lib/chef-dk/policyfile_compiler.rb
spec/unit/policyfile/cookbook_location_specification_spec.rb
spec/unit/policyfile_demands_spec.rb

When I was working on delivery I got quite a ways through the pipeline before I found that I had an incorrect item in my run list. Since the cookbooks are available locally, we should check this when you run `chef install` to save you the time.
Fixes #629
@chef/workflow

Ensure runlist recipes exist

---

omnibus/config/projects/chefdk.rb

Yup.
/cc @chef/client-dev-tools @chef/engineering-services

Consume master of fauxhai

---

omnibus/config/projects/chefdk.rb

There has been no recent activity and master is pointing to the same commit that 1.6.1 was released at.

Point knife-spork to master until knife-spork#198 is fixed

---

.travis.yml
Gemfile
appveyor.yml
omnibus/config/projects/chefdk.rb
omnibus/config/software/chefdk.rb
omnibus/config/software/r-train.rb

From 2.9.2 to 3.0.2.  The main goal of this branch (right now) is to generate a working package that we can test with.
Before this could be merged we would need to update and probably release the following projects
* Test Kitchen (change already in master, just needs 1.5.0 release)
* R-train (needs a branch merge and release)
* The software definition can be deleted after it is released
* Chef (needs a branch merge and release)
* Chef Provisioning (needs a branch merge and release)
* Berkshelf (needs a branch merge and release)
I _think_ the above is the order they need releasing it, but we'll need to test that.  There are circular dependencies between a lot of these.
Fixes https://github.com/chef/chef-provisioning/issues/446

Testing out the update of net-ssh

---

lib/chef-dk/policyfile/dsl.rb
spec/unit/policyfile_evaluation_spec.rb

* fix a typo in the error message that was already there
* add special case handling for when the user separates cookbook and recipe with a single colon instead of two.

Better invalid run list errors

---

README.md

El Capitan protects `/usr/bin` and prevents users writing files there so the installer puts the symlinks to run chef, knife etc into `/usr/local/bin`. This commit updates the README's install instructions to reflect this.
Note: I didn't have a pre-El Capitan machine to test with (it could be that all installers use `/usr/local/bin` so all that is required is the addition of `local/` rather than the alternation in the instructions).

Update uninstall instructions for OS X El Capitan

---

POLICYFILE_README.md
lib/chef-dk/policyfile/cookbook_locks.rb
lib/chef-dk/policyfile_services/export_repo.rb
lib/chef-dk/policyfile_services/push_archive.rb
lib/kitchen/provisioner/policyfile_zero.rb
spec/unit/policyfile/cookbook_locks_spec.rb
spec/unit/policyfile_lock_serialization_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb
spec/unit/policyfile_services/push_archive_spec.rb

Changes `chef export` to create "native format" Chef repos; that is, it creates a Chef repo with `cookbook_artifacts`, `policies`, and `policy_groups` which Chef Zero/local mode will serve over the native policyfile APIs instead of using compat mode. I have confirmed that this fixes https://github.com/sethvargo/chef-sugar/issues/114 in addition to improving usability by making Chef Client configuration work the same as it does when using erchef.
In order to actually use "native format" policy repos with local mode, you need Chef Client with this patch: https://github.com/chef/chef/pull/4479 and a Chef Client or ChefDK package with the latest Chef Zero. Therefore it's probably best to not ship this until Chef 12.7 ships, or else I can rework this patch to provide a compatibility option.

Native policy export

---

omnibus/config/projects/chefdk.rb

add pry, pry-byebug, pry-remote to chef-dk

---

lib/chef-dk/command/export.rb
lib/chef-dk/policyfile_services/export_repo.rb
lib/chef-dk/policyfile_services/push_archive.rb
spec/unit/command/export_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb
spec/unit/policyfile_services/push_archive_spec.rb

Fixes some issues with error messages in the `chef export` command, adds a README to the generated repository, moves the generated configuration to `.chef/config.rb` so you don't need to pass `-c` to `chef-client`, and adds a "next step" instruction to `chef export`.

Fixup chef export

---

omnibus/config/projects/chefdk.rb

Update to the latest.  For Rubocop this resolves several annoying / nasty bugs that create false alerts and break autocorrect.

Update rubocop and chef-provisioning-* deps

---

ci/verify-chefdk.bat
ci/verify-chefdk.sh

Sometimes tests crash and don't clean up their symlinks; some tests don't clean up their symlinks at all. This makes it a non-issue by removing all the things.

Create a custom TEMPDIR and blow it away before and after tests

---

omnibus/config/projects/chefdk.rb

The gemfile for v0.11.0 was pointing at a branch that no
longer exists. Bundler would try to fetch it and fail.
This has been fixed in master.

Bump kitchen-inspec to master

---

lib/chef-dk/version.rb
omnibus/config/projects/chefdk.rb

Pin berkshelf to a commit that bumps up chef config to 12.7.2 to work around a delivery issue.
Also bump chef-dk version to 0.11.1 for a new release.
@jaym @tyler-ball @chef/client-core

Update berkshelf pin and chefdk version

---

omnibus/config/projects/chefdk.rb

Pin kitchen-inspec for chef-dk patch release.
@chef/omnibus-maintainers @jaym

Unfloat kitchen-inspec to v0.11.0

---

CONTRIBUTING.md
POLICYFILE_README.md
lib/chef-dk/command/clean_policy_cookbooks.rb
lib/chef-dk/command/clean_policy_revisions.rb
lib/chef-dk/command/delete_policy.rb
lib/chef-dk/command/delete_policy_group.rb
lib/chef-dk/command/export.rb
lib/chef-dk/command/install.rb
lib/chef-dk/command/push.rb
lib/chef-dk/command/push_archive.rb
lib/chef-dk/command/show_policy.rb
lib/chef-dk/command/undelete.rb
lib/chef-dk/command/update.rb
lib/chef-dk/command/verify.rb
lib/chef-dk/skeletons/code_generator/templates/default/Policyfile.rb.erb
omnibus/README.md
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/policyfile_spec.rb
spec/unit/policyfile_lock_build_spec.rb

Sync the contributing doc with chef/chef doc (where it makes sense) and update the github URLs to the new orgs.

Update contributing doc and Github URLs

---

omnibus/config/projects/chefdk.rb

This change fixes issues with FC058 producing false
positives.

Update foodcritic to v6.0.1

---

.travis.yml
omnibus/config/projects/chefdk.rb

This should get rid of the CookieManager warning

bumping berkshelf version to 4.2.1

---

omnibus/config/projects/chefdk.rb

Cleaning up un-used .a files at build time.
@chef/client-core @lamont-granquist

Clean up static libs at build time

---

omnibus/resources/chefdk/msi/source.wxs.erb

We use powershell.exe to launch a script that itself launches conemu or powershell with `chef shell-init powershell` to initialize the shell environment. When we use powershell.exe, we don't specify `-noprofile`, which results in powershell needlessly running the current profile (which may be slow depending on what's in it). Using `-noprofile` speeds things up since that powershell.exe instance itself is throwaway and profile customizations are never used since there is no interaction of that shell with the user.

Improve Chef-DK shortcut startup time by skipping powershell profile

---

ci/verify-chefdk.bat
ci/verify-chefdk.sh

Similar to https://github.com/chef/chef/commit/01147dc69cf1f62b03400e3292c5d7c5d5d7e95f
We need to run the test command last to ensure the exit code passed to
the Ci system is the one from the tests.

Ensure tests are last command in test scripts

---

lib/chef-dk/policyfile_services/export_repo.rb

Uses the new `#all_files` entry in `CookbookVersion` (and `Loader`) so that other files in cookbooks (like spec and test) will be included in the export and make their way into a test kitchen instance.

Include non segments in export

---

lib/chef-dk/component_test.rb
spec/spec_helper.rb

Rubygems 2.6.2 just came out and seems to have a minor incompatibility with bundler 1.11.2. I'm not very sure at all there isn't a better way to workaround it, but this does work.

Gem version borkage

---

CHANGELOG.md
Rakefile

I also updated the rake task so that the changelog generator doesn't rely on your git remote being named "origin".

Changelog for 0.12.x

---

lib/kitchen/provisioner/policyfile_zero.rb

This fixes https://github.com/test-kitchen/test-kitchen/issues/930 and is in line with builtin TK provisioners.

Fix windows powershell command by prefixing run_command with call operator

---

omnibus/config/projects/chefdk.rb

/cc: @tyler-ball 
Similar to https://github.com/chef/chef/pull/4811 this fixes broken chefdk build by pointing to the right LICENSE file.

Point to the right license file for chefdk.

---

.bundle/config
.gitignore
.travis.yml
README.md
Rakefile
appveyor.yml
tasks/bundle.rb
tasks/bundle_util.rb
tasks/dependencies.rb

Add "rake bundle[<args>]" task to unfreeze and work with file

Check in .bundle/config --without omnibus_package --frozen

---

Gemfile
Gemfile.lock
Gemfile.windows.lock
acceptance/Gemfile.lock
omnibus/Gemfile.lock

This is to make sure that delivery is using the pending Chef release of 12.9.38
\cc @jkeiser @danielsdeleo @randomcamel @chefsalim

Dependency bump to get the latest Chef release, 12.9.38

---

lib/chef-dk/command/verify.rb
omnibus/config/projects/chefdk.rb
omnibus/config/software/delivery-cli.rb
omnibus/config/software/rust-uninstall.rb
omnibus/config/software/rust.rb
omnibus/omnibus.rb
omnibus/package-scripts/chefdk/postinst
omnibus/package-scripts/chefdk/postrm

This includes the delivery CLI tool in the chefdk package.
Pending: 
Ping @tyler-ball 
Still outstanding:
* windows build
* determining whether to include cargo to allow
unit tests to be run in verify.
Note for Reviewers: 
THis PR is  against the set of related changes in the branch `unified_workflow_spike`, and not against `master`. 
Reference: https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=174&projectKey=UW&selectedIssue=UW-1

add delivery-cli to chefdk

---

ci/verify-chefdk.bat

\cc @tylercloke @sersut @schisamo 
On our Windows builders we were seeing the following text:
```
============================================================
Running verification for chefdk
============================================================
Checking for existence of binfile `berks`...
...FOUND IT!
Checking for existence of binfile `chef`...
...FOUND IT!
Checking for existence of binfile `chef-client`...
...FOUND IT!
Checking for existence of binfile `kitchen`...
...FOUND IT!
Checking for existence of binfile `knife`...
...FOUND IT!
Checking for existence of binfile `rubocop`...
The system cannot find the batch label specified - error
```
It was failing out without actually running `chef verify`. We also no longer need to check for those binfiles because we do that in `chef …

We were not actually running chef verify on Windows

---

lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

The example version value for require_chef_omnibus was 12.5.0, which was never actually released. This changes the value to an actual released version just for sanity. This is just something which was bothering me and I had to fix.

Update require_chef_omnibus example in template.

---

Gemfile
Gemfile.lock
spec/unit/tasks/helpers_spec.rb
tasks/dependencies.rb
tasks/helpers.rb
version_policy.rb

To bring how we handle this dependency in line with other dependencies in the ChefDK
\cc @randomcamel @mwrock @PrajaktaPurohit

Only consume push jobs client with version from the stable channel

---

RELEASE_NOTES.md

\cc @btm @mwrock @PrajaktaPurohit @randomcamel

Adding release notes about the lack of Delivery CLI in 0.14 Windows packages

---

lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

By default, Inspec returns output in rspec's terse progress format. This PR updates the cookbook generator so that the commented Inspec verifier block now defaults instead to rspec's more verbose documentation format.
This will provide the informative test output that people are used to seeing from Serverspec.

Generated .kitchen.yml defaults Inspec to doc format output

---

lib/chef-dk/helpers.rb
spec/unit/helpers_spec.rb

This includes helpful unix tools like ssh, scp, etc. Once a Windows users has ran our custom desktop shortcut or `chef shell-init powershell` then they will have access to these tools. I put it at the end of the path because some of these tools are already bundled into the ChefDK.
@tpetchel @randomcamel @btm @schisamo @ksubrama @PrajaktaPurohit

Adding the Git for Windows tools to the path if they are present

---

acceptance/Gemfile.lock
ci/verify-chefdk.sh

All chef-acceptance logs and generated data is now properly archived with the job:
http://manhattan.ci.chef.co/job/chef-test/6/architecture=x86_64,platform=acceptance,project=chef,role=tester/artifact/chef-acceptance-data/
These changes were tested in the following ad hoc build:
http://manhattan.ci.chef.co/job/chefdk-test/183/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/console
/cc @chef/engineering-services @adamedx @btm @mwrock @PrajaktaPurohit @ksubrama

Re-enable and fix acceptance test

---

omnibus/.kitchen.yml
omnibus/README.md

This ensures the Omnibus build is executed in 32-bit mode which matches how we currently build ChefDK in our pipeline.
/cc @tyler-ball @ksubrama
Now that we released the updated omnibus cookbook to supermarket.chef.io this is the only change we need to ensure people are executing local/dev Omnibus builds in 32-bit mode on Windows.

Update naming of Windows instance to include `*-i386`

---

ci/verify-chefdk.sh

This will ensure we actually exit on all failed commands. We'll also add the `-v` and `-x` options so behavior matches Chef's verify script.
/cc @chef/engineering-services @mwrock @adamedx @ksubrama @btm @PrajaktaPurohit @tyler-ball

Move `set` to beginning of `verify-chefdk.sh` script

---

ci/verify-chefdk.sh

I'm piping from find because there were so many items.
I have run this through an ad hoc build which has wiped the cruft off all existing testers.

clean up leftover test cruft

---

lib/chef-dk/cli.rb
spec/unit/cli_spec.rb

The change properly handles the two different version string formats a `delivery --version` command can return:
```
$ delivery --version
delivery master (454c3f37819ed508a49c971f38e42267ce8a47de)
$ delivery --version
delivery 0.0.15 (454c3f37819ed508a49c971f38e42267ce8a47de)
```
The updated ChefDK version output looks like:
```
$ chef --version
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
delivery version: master (454c3f37819ed508a49c971f38e42267ce8a47de)
berks version: 4.3.3
kitchen version: 1.8.0
```
/cc @charlesjohnson @tyler-ball @ksubrama

`chef --version` should print the Delivery CLI version

---

lib/chef-dk/command/export.rb

`chef export`'s usage is incorrect. It states a `client.rb` will be in created in the root of the export and includes `-c client.rb` in the example. `export` actually creates a `.chef/config.rb` and can be invoked with the simpler `chef-client -z`.
The message after the export command completes is correct. This PR corrects it here too.
Obvious fix.

Correct chef export usage message

---

Gemfile
Gemfile.lock
tasks/bin/bundle-platform
tasks/bundle_util.rb

As of bundler 1.12.0, running our rake bundler tasks wipes out the windows dependencies when run on mac/linux and wipes out the non-windows dependencies when run on windows. This change can be narrowed down to a change to the `gemspec` DSL in [this one line](https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L71). v1.12.0.pre.1 added the `platform` parameter. Removing that parameter duplicates the behavior we see in 1.11.2. We can get this same behavior by not using `gemspec` and calling `gem` instead via `path: "."`.
I'm not crazy about this trickery but it appears to be the best way to support 1.12.4 and beyond.

fix bundle locking on bundler 1.12

---

lib/chef-dk/command/verify.rb
omnibus/config/software/chef-dk-appbundle.rb
omnibus/files/chef-dk-appbundle/build-chef-dk-appbundle.rb
omnibus/files/chef-dk/build-chef-dk.rb
spec/unit/gemfile_util_spec.rb
tasks/gemfile_util.rb

(Only using this branch as a test branch - if that passes, we can merge in the original PR)

Rubocop should install to chefdk/bin

---

Gemfile
chef-dk.gemspec
ci/bundle_install.sh

Removes dependencies on many native gems (reliability)
Doesn't install bundle unless it has to (speed)

Install fewer gems when bumping chef-dk.

---

ci/verify-chefdk.bat
lib/chef-dk/command/verify.rb
omnibus/.kitchen.yml
omnibus/Berksfile
omnibus/Gemfile.lock
omnibus/config/software/chef-dk-complete.rb
spec/unit/command/verify_spec.rb

\cc @danielsdeleo @tylercloke @mwrock @ksubrama

Build Delivery CLI on Windows using msys2 build toolchain

---

lib/chef-dk/command/generate.rb
lib/chef-dk/command/generator_commands/build_cookbook.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/files/default/build-cookbook/.kitchen.yml
lib/chef-dk/skeletons/code_generator/files/default/build-cookbook/README.md
lib/chef-dk/skeletons/code_generator/files/default/build-cookbook/test-fixture-recipe.rb
lib/chef-dk/skeletons/code_generator/files/default/delivery-config.json
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/build-cookbook/Berksfile.erb
lib/chef-dk/skeletons/code_generator/templates/default/build-cookbook/metadata.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/build-cookbook/recipe.rb.erb
spec/unit/command/generator_commands/build_cookbook_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

* Add new option `-d`/`--delivery` to `chef generate cookbook`, which will create a `.delivery/config.json` and build cookbook in the generated cookbook.
* Add new generator subcommand, `chef generate build-cookbook`, which creates the `.delivery` content as above, but outside the context of generating a new cookbook. This includes the same auto-detection logic as [pcb](https://github.com/chef-cookbooks/pcb) to determine if the project is a cookbook or not, and modify the generated content accordingly. Therefore, it can potentially replace the pcb cookbook's role in `delivery init`.
For both use cases, I compared the generated files to those created by `delivery init -l`, and confirmed there are no substantive differences.

Generate delivery config

---

lib/chef-dk/command/generator_commands/build_cookbook.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/shared/custom_generator_cookbook.rb
spec/shared/setup_git_committer_config.rb
spec/unit/command/generator_commands/build_cookbook_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

* `chef generate cookbook` (default mode) will commit files to master when it detects that you want it to initialize a new git repo
* `chef generate cookbook -d` (delivery mode) will make one commit for `.delivery/config.json`, and another commit for the build cookbook. These commits are done in a feature branch which is merged (with `--no-ff` to force a merge commit) and then cleaned up.
* After `chef generate cookbook` the user now sees a message telling them to `cd` into the cookbook's directory to get started.

Create cookbooks with exemplary git history

---

lib/chef-dk/chef_runner.rb
lib/chef-dk/command/generator_commands/base.rb
lib/chef-dk/command/generator_commands/chef_exts/generator_desc_resource.rb
lib/chef-dk/command/generator_commands/chef_exts/quieter_doc_formatter.rb
lib/chef-dk/command/generator_commands/chef_exts/recipe_dsl_ext.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/unit/chef_runner_spec.rb
spec/unit/command/generator_commands/chef_exts/generator_desc_resource_spec.rb
spec/unit/command/generator_commands/chef_exts/recipe_dsl_ext_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Output of `chef generate cookbook` looks like this:
```
shell$ chef generate cookbook foo -d     
Generating cookbook foo
- Ensuring correct cookbook file content
- Committing cookbook files to git
- Ensuring delivery configuration
- Ensuring correct delivery build cookbook content
- Adding delivery configuration to feature branch
- Adding build cookbook to feature branch
- Merging delivery content feature branch to master
Your cookbook is ready. Type `cd foo` to start working.
```
* Add a `silence_chef_formatter` method to the recipe DSL, which works by changing the formatter to the `null` formatter. This makes the concise output mode opt-in. The intention is to not change the output for users with existing custom generator cookbooks unless/until they modify their cookbooks to have …

make cookbook generator output more concise

---

lib/chef-dk/skeletons/code_generator/files/default/serverspec_spec_helper.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_spec.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/serverspec_default_spec.rb.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Do not merge until 0.15.x ships.
Changes the cookbook generator so that the default verifier is now Inspec.
- Updates generated .kitchen.yml
- Generates Inspec-style test folder structure in cookbook skeleton
- default_spec.rb now refers to Inspec documentation, no longer includes spec_helper.rb
- No longer generates serverspec/spec_helper.rb
- Resolves #834

Change generator default verifier to Inspec

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Adds `-V` / `--verbose` option to turn doc formatter output back on for `chef generate cookbook`. I picked `-V` because it's consistent with `knife`.

Add verbose flag for `generate cookbook`

---

lib/chef-dk/command/generator_commands/cookbook.rb
spec/unit/command/generator_commands/cookbook_spec.rb

It is time to remove the flag `-d` from `chef generate cookbook`command, not it will be the default behavior.
cc/ @tyler-ball @danielsdeleo @tylercloke

[UW-65] Remove & make the `-d` flag the default behavior

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

This is a much better way to do this vs. the copy / paste issue template
in the contributing doc

Add a Github issue template

---

lib/chef-dk/skeletons/code_generator/recipes/template.rb
spec/unit/command/generator_commands/template_spec.rb

Removes the default folder from the template generator.
Resolves #183.
Signed-off-by: Charles Johnson <charles@chef.io>

Remove default folder in template generator

---

lib/chef-dk/command/verify.rb
lib/chef-dk/helpers.rb
omnibus/Gemfile
omnibus/Gemfile.lock
omnibus/config/software/chef-dk-complete.rb
omnibus/config/software/git-custom-bindir.rb
omnibus/config/templates/git-custom-bindir/config.mak.erb
spec/unit/helpers_spec.rb

So we do not overwrite user's Git
\cc @danielsdeleo @tylercloke @charlesjohnson @afiune 
Fixes https://github.com/chef/chef-dk/issues/854
I realize this is the OPPOSITE of the solution we want, but I want to do this for now and then address the real fix when we have time to in July/August.

Putting the custom git binary folder at the end of the path

---

Gemfile
Gemfile.lock

activesupport 5 requires Ruby 2.2.2 or later. Until chefdk runs on 2.2.X
we need to stick with the 4.X release. This also bumps the deps to bring
in the latest chef-zero and ohai releases.

Update deps and lock activesupport <5

---

lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb

Do not hard code the cookbook name. Instead use no-name so that
end-users can generate a generator that is not `code_generator`

Fix recipe in code_generator skeleton

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Now `chef generate cookbook` creates a `.delivery/project.toml` file
that is a prototype for our newest `delivery local [phase]` command
(comming up) that will do the execution of configurable local phases
on your workstation.

Update cookbook generator to create project.toml

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/recipe.rb
lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_spec.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_test.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/recipe_spec.rb

+ mv test/integration/default/default_spec.rb -> test/recipes/default_test.rb.
+ Update the default inspec test to support windows and nix.
+ Remove doc inspec format from .kitchen.yml.
+ Have `chef generate recipe <path> <recipe_name>` make a test/recipes/<recipe_name>.rb file with the updated default inspec test content.

Fix up inspec generated content.

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb
spec/unit/command/generator_commands/cookbook_spec.rb

They are only used by cookbooks uploaded to Supermarket so users need to opt into this. Put an example in metadata.rb
Just a note: Ideally, Supermarket would be the one to enforce these rules.
\cc @danielsdeleo @afiune @tylercloke

Disable foodcritic rules which check for issues_url and source_url in metadata.rb

---

lib/chef-dk/skeletons/code_generator/files/default/chefignore

Resolves an issue where the Policyfile.lock.json is included as an input
to a cookbook's identifier hash so changes to informational-only
information (such as git commits) causes the `revision_id` to be
updated.
Addresses one of the issues in https://github.com/chef/chef-dk/pull/880

Add policyfile stuff to chefignore

---

Dockerfile

Add a Dockerfile to Chef-DK to promote better use of Chef in Docker-based pipelines and allow for testing newer (or older) versions of Chef-DK without having to install to your system.
Note: `git config` is required for the omnibus build. I'm happy to update this to better values, though I don't believe these values actually persist anywhere in the image.
Output of a docker build using this Dockerfile:
```
kreedy@Kevins-iMac:~/Projects/kevinreedy/chef-dk$ git log --pretty=oneline | head -n 3
ab09aeb9b8022d039a4d4b00d3f368c19be18e0e Add Dockerfile
ca00f402aef82b6d67a00962b15e8e6186474179 Bump version of chef-dk to 0.17.3 by Chef Versioner.
e0372f5e005facb303439fe30d2c0dc0d31d88bb Merge pull request #942 from chef/afiune/FLOW-444/consume-delivery-truck-from-supermarket …
```

Add Dockerfile to Chef-DK

---

lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

(We will likely change the location in the future to avoid this
directive, but for now want the current location to work.)

Add .kitchen.yml to find generated inspec tests.

---

omnibus/config/software/chef-dk-complete.rb

From what I can tell by looking at jenkins build logs, Windows is the only platform where actual files are deleted by this build delendency defined [here](https://github.com/chef/omnibus-software/blob/master/config/software/clean-static-libs.rb). The files deleted on Windows are:
```
Deleting C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep-selector-libgecode-1.3.1/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodedriver.a
Deleting C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep-selector-libgecode-1.3.1/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodeint.a
Deleting C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep-selector-libgecode-1.3.1/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodekernel.a
Deleting …
```

Keep static libraries deleted in jenkins builds

---

omnibus/config/software/chef-dk-cleanup.rb
omnibus/config/software/chef-dk-complete.rb
omnibus/files/chef-dk/build-chef-dk.rb

We currently clean up bundler's `git`-based gem directory in the `chef-dk` software definition. However, the `chef-dk-appbundler` software definition runs afterward and can put things back in there. To fix this, we now clean bundler's directories after chef-dk-appbundler, in a separate step. We merged this with the chef-remove-docs step.

Actually remove bundler git/path-sourced gem files

---

lib/chef-dk/command/generator_commands/build_cookbook.rb
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb

Added option --for to build_cookbook generator to use branch other than master.
This will allow delivery-cli to use non-master pipelines in delivery init.

Added option --for to build_cookbook generator to use branch other than master

---

omnibus/config/software/git-custom-bindir.rb

This fixes builds on Debian and Ubuntu that were failing for me while trying to build in Docker. Previous to this, the `make distclean` would fail, as `make` was not in the path:
```
[Software: git-custom-bindir] I | 2016-10-13T16:07:15+00:00 | Building because `preparation' dirtied the cache
[NetFetcher: git-custom-bindir] I | 2016-10-13T16:07:15+00:00 | Cleaning project directory `/var/cache/omnibus/src/git-custom-bindir'
[NetFetcher: git-custom-bindir] I | 2016-10-13T16:07:15+00:00 | Extracting `/var/cache/omnibus/cache/git-2.8.2.tar.gz' to `/var/cache/omnibus/src/git-custom-bindir'
[Builder: git-custom-bindir] I | 2016-10-13T16:07:15+00:00 | Starting build
[Builder: git-custom-bindir] I | 2016-10-13T16:07:15+00:00 | Environment:
[Builder: git-custom-bindir] I | …
```

Pass environment to make distclean while building git

---

chef-dk.gemspec

We removed CONTRIBUTING.md, so we need to update the gemspec.

Remove CONTRIBUTING.md from gemspec

---

lib/chef-dk/command/generator_commands/base.rb
spec/unit/command/generator_commands/base_spec.rb

Since only `git.bat` is found in the `PATH` on Windows ChefDK installs:
https://github.com/chef/omnibus-software/blob/master/config/software/git-windows.rb#L50-L52
`have_git?` improperly returns false because it only looks for an executable with an `.exe` extension. This commit modifies the method to also search for extensions found in the `PATHEXT` env variable.
http://environmentvariables.org/PathExt

Check for other git path extensions besides ‘.exe’

---

Gemfile.lock

Ad-Hoc build: http://manhattan.ci.chef.co/job/chefdk-build/762/
/cc @tduffield

Update mixlib-install to 2.1.6 and berkshelf to 5.2.0

---

lib/chef-dk/command/verify.rb
omnibus/package-scripts/chefdk/postinst

Fixes #1070.
/cc @chef/client-core @lnxchk @chef/inspec-maintainers

Link inspec bin to /usr/bin (and /user/local/bin on MacOS)

---

.bundle/config
Gemfile
Gemfile.lock

For users interacting with a Chef-Server without using Manage, knife-opc
would be the first option -- so it should be included in chefdk, since
this is the package (new) users install to get started.
First, I had added knife-opc to lockdown_gem's, but apparently, its
Gemfile.lock contains dependencies of the development group, making this
impossible: "Build chef-dk-appbundle" would fail trying to find the 'sdoc'
dependency.
Even without the `lockdown_gem "knife-opc"`, I tried adding `knife opc
user list --help` as a component smoke test, however, since this exits
with 1 even when everything is installed properly, it wouldn't make a
good smoke test. So I've left that off again.
I've seen #1069 just now -- I can rebase this after that change is merged and apply its changes -- do we want to …

Add knife-opc to chefdk

---

Gemfile.lock
RELEASE_NOTES.md
lib/chef-dk/version.rb
tasks/version.rb

* Add rake tasks for bumping major/minor versions
* Bump major version to 1.0

Bump ChefDK to 1.0 (and associated changes)

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-config.json
spec/unit/command/generator_commands/cookbook_spec.rb

Updates the `config.json` generated by `chef generate cookbook / build-cookbook` to contain:
```
{
...
"job-dispatch": {
"version": "v2"
},
...
}
```
in place of `build_nodes`.

Default cookbook generation of delivery config to new job dispatch system.

---

tasks/version.rb

Automate the process of resetting the release notes after a major/minor version bump.
* Prevents the misunderstanding of #1080 from happening. 

Reset RELEASE_NOTES when version is bumped

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-config.json
spec/unit/command/generator_commands/cookbook_spec.rb

We had a typo here. Should be `job_dispatch`, not `job-dispatch`
\cc @rmoshier @dmccown @tylercloke 
N/A

The Workflow V2 job dispatch key should be with an underscore

---

lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb

This changes updates the commentary that describes two metadata attributes:  `issues_url` and `source_url`.
None
I'm not sure this warrants an update to the RELEASE\_NOTES.md but am happy to add something if you think it's warranted.
There are no tests for this as it's simply a change to code comments.
The `issues_url` and `source_url` are, indeed, helpful when the cookbook
is published to a Supermarket.  Even when they aren't, consumers of this
cookbook may want to know where the source code is stored and/or where
issues for this cookbook are tracked.
This changes updates the commentary that describes these two metadata
attributes.
Signed-off-by: Nathen Harvey <nharvey@chef.io>

These metadata fields are always helpful.

---

Gemfile
Gemfile.lock
omnibus/config/software/chef-dk-appbundle.rb

Add @coderanger's DCO utility to ChefDK. https://github.com/coderanger/dco
#1052 was blocked due to a rebase/merge conflict. This is something I think is useful to get in, so I duplicated the work on a branch we had control over.

Add `dco` command line utility to easier management of DCO sign-offs

---

RELEASE_NOTES.md
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/recipe.rb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/recipe_spec.rb

Storing generated inspec tests in `test/recipes` causes Foodcritic to
fail, as Foodcritic assumes the `test` directory is now a
cookbook (which is false). Using `test/smoke/default` fixes this issue
and creates direct associations with the existing Kitchen and Workflow
templates.
1. The delivery-project.toml already runs `kitchen verify` during
smoke. There is now a connection between the phase and the tests that
are run by default.
2. The `default` folder in smoke is associated with the `default` suite
already provided in the Kitchen YAML. This indicates and guides the user
that additional suites can be created under smoke, and gives implicit
guidance as to their naming.
* COOL-585

chef: Use `test/smoke/default` instead of `test/recipes` for generated cookbooks/recipes

---

lib/chef-dk/generator.rb
lib/chef-dk/skeletons/code_generator/templates/default/build_cookbook/recipe.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/generator_spec.rb

The format we use here is mostly a leftover from rdoc as far as I can tell, but we’re not even consistently using that format at the moment. Fields with :: will get parsed by YARD. For a time we used Copyright:: and we seem to have slowly removed that. We should be using that format in cookbooks since it’ll get parses. Also “Cookbook Name” makes no sense when every other field omits “Name”. It should just be “Cookbook”

Generate content with the proper yard parsable headers

---

Gemfile

Depend on mixlib-install on two gem groups

Depend on mixlib-install on two gem groups

---

ci/version_bump.sh

We don't want to fail the version bump if the changelog update fails.

Dont fail the version bump if changelog fails

---

Gemfile.lock
RELEASE_NOTES.md

kitchen-dokken 1.0.9 now defaults to using the chef/chef Docker image.

kitchen-dokken: Default to official `chef/chef` image

---

DOC_CHANGES.md

We're not doing this anymore. We add the release notes to the docs site instead

Remove the old doc changes doc

---

lib/chef-dk/skeletons/code_generator/templates/default/repo/gitignore.erb

This is a first commit in a series to add comments to common files resulting from a chef hackday
Most of the comments shamelessly borrowed from (https://github.com/mwrock/chef_workstation)

Document chefignore

---

lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/metadata.rb

- added maintainer field
- added maintainer_email field
- added license field
If you don't have these fields if you attempt to upload this cookbook this error happens:
```
15:55:39 JJs-MacBook-Pro vmware_playground > (master) knife cookbook upload example
Uploading example        [1.0.0]
ERROR: The data in your request was invalid
Response: Field 'metadata.maintainer' invalid
```
Signed-off-by: JJ Asghar <jj@chef.io>

Adding maintainer and email fields to example

---

lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb

- added a not_if guard to the generator to avoid attempting to create the branch if it already exists

guard against branch already existing when creating a build cookbook

---

lib/chef-dk/policyfile/storage_config.rb
spec/unit/policyfile/storage_config_spec.rb
spec/unit/policyfile_services/push_spec.rb

Whenever you load a policyfile by name, if you specified a lockfile
instead of the policyfile, this change will change the filename to the
matching .rb file instead rather than exiting with an error.
This allows you do to things like `chef push prod mypolicy.lock.json`
instead of `chef push prod mypolicy.rb`.

Accept foo.lock.json as well as foo.rb when loading a policyfile

---

Gemfile

cc @tyler-ball 
Due to a bug in Rubygems, we need to ensure that the `rake` gem is installed. 
* Should fix failing acceptance tests

Ensure rake is installed via the CI tools

---

ci/verify-chefdk.sh

We currently run both chef and chef-dk acceptance tests under ChefDK. This is causing a problem because stable chef (12.18.31) does not have the necessary fixes for the rainbow/rubygems bug we're currently dealing with. To avoid this issue, and save some time on acceptance tests, we are (temporarily?) disabling chef acceptance tests and running only chef-dk acceptance tests.

Do not run Chef Acceptance tests

---

HISTORY.md

To ensure that the CHANGELOG is accurate, add the 1.1.16 changelog to HISTORY.md

Fix HISTORY.md to include 1.1.16 changelog

---

Dockerfile
Rakefile
ci/version_bump.sh

To avoid the potential race condition between build and omnitruck,
install ChefDK directly via packages.chef.io. Included with this
is a simply handler to keep the Dockerfile up to date.

[Dockerfile] Install ChefDK via packages.chef.io

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
spec/unit/command/generator_commands/cookbook_spec.rb

We have encountered a problem when users install ChefDK for the first time and they do not have it on its `PATH` env variable, they end-up with the following behavior:
```
$ chef generate cookbook test
$ cd test
$ delivery local unit
Chef Delivery
Running Unit Phase
thread 'main' panicked at 'Unexpected error: Failed to execute process: No such file or directory (os error 2)', src/delivery/command/local.rs:53
```
The main problem is that the `project.toml` doesn't have the prefix `chef exec` to run the unit phase in the context of ChefDK. 
This change is adding the prefix to the default generated `project.toml` so if the user doesn't have ChefDK configured on its PATH, it wont matter and you will be able to run all phases.
```
$ delivery local unit
Chef Delivery
Running Unit Phase
. …
```

Fix `delivery local` failures by adding 'chef exec' prefix to all commands in project.toml

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/.kitchen.yml
lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/test-fixture-recipe.rb
lib/chef-dk/skeletons/code_generator/templates/default/build_cookbook/Berksfile.erb
spec/unit/command/generator_commands/cookbook_spec.rb

The delivery-base and delivery_build cookbooks are no longer required for Automate Workflow. To test a build cookbook, all you need is the ChefDK! Update the build-cookbook generator to use ChefDK as the kitchen base rather than the Chef Client.
The GIT_DISCOVERY_ACROSS_FILESYSTEM is necessary for the command to
work successfully, since the cookbook under test is on a volume.

Use ChefDK, rather than Chef Client, as build-cookbook Test Kitchen base

---

lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_test.rb.erb

Having a `skip` parameter in your describe block does not mean that the entire describe block is skipped. Instead, we need to use the `:skip` flag.
* Internal Ticket COOL-664

Properly skip generated skeleton Inspec tests

---

.travis.yml
Gemfile
Gemfile.lock

When we added chefstyle we accidentally dropped cookstyle to a very old release. We’re pinning a minimum version now to avoid ever doing that again. Also we’re removing chefstyle from DK. In the ideal world we’d run DK through Chefstyle, but we don’t want to ship chefstyle with DK. There’s already a huge amount of confusion with customers as to the difference between our two linters. Shipping both with DK would make that much much worse. Let’s avoid the whole problem.

Remove chefstyle from DK and pin cookstyle with a minimal version

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb
spec/unit/command/generator_commands/build_cookbook_spec.rb

Before this change if a user ran `chef generate build-cookbook .` on a
delivery project that has already a `project.toml` and/or `config.json`
both files would get overwritten.
This change fixes this problem by adding a `not_if` guard.
COOL-653 / ZD 10945

Avoid override existing delivery configuration

---

Gemfile
Gemfile.lock

The failures with ServerSpec have been resolved.

Use kitchen-dokken 2.1.x

---

lib/chef-dk/generator.rb

Better error messaging when license is invalid

---

README.md

We killed berkshelf.com and chefspec.org isn’t a thing

Fix links to the Chefspec and Berkshelf site

---

lib/chef-dk/command/generator_commands/cookbook_code_file.rb

When checking for a cookbook's validity, we should only look for
metadata.rb; recipes or any other directory are not required.
cc @chef/maintainers

A cookbook may not contain a recipe

---

omnibus/config/software/chef-dk-complete.rb

Something in the installation of devkit munges the ruby environment of the build itself, which causes any defs after that to fail with strange pathing issues. This moves it to the end of the build so that it won't cause issues.

"build" devkit last

---

lib/chef-dk/skeletons/code_generator/templates/default/build_cookbook/metadata.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb
spec/unit/command/generator_commands/build_cookbook_spec.rb

Without this these are going to fail foodcritic. The 12.1+ is common sense at this point

Require Chef 12.1+ in the skeleton cookbook and use chef_version

---

lib/chef-dk/skeletons/code_generator/recipes/recipe.rb
spec/unit/command/generator_commands/recipe_spec.rb

Previously the smoke test had the same name as the recipe.  This changes
that so that the smoke test will match `#{context.new_file_basename}_test.rb`
Signed-off-by: Nathen Harvey <nharvey@chef.io>

Smoke tests always end with `_test.rb`

---

.travis.yml
chef-dk.gemspec

We’re shipping on 2.3 anyways and will be shipping on 2.4 in the near future. I’m not sure what the goal of 2.2 support was really since we tell people to use the package. Seems like this just makes testing take longer.

Remove support for Ruby 2.2

---

Gemfile.lock

We need a release of ChefDK in current that has the latest cookstyle and foodcritic. Right now if someone does the right thing with amazon for Chef 13, then travis goes red since old Foodcritic blows up.

Bump cookstyle and foodcritic deps

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
spec/unit/command/generator_commands/cookbook_spec.rb

Depends on https://github.com/acrmp/foodcritic/pull/462
TODO:
\cc @afiune @charlesjohnson @danielsdeleo @tylercloke

Updating the delivery local syntax test to use the new defaults introduced

---

omnibus/Gemfile.lock
omnibus/config/software/chef-dk.rb
omnibus/config/software/git-custom-bindir.rb
omnibus/files/chef-dk-gem/build-chef-dk-gem.rb

we still have iconv in chef-dk due to git

remove iconv from ruby build

---

lib/chef-dk/cli.rb
spec/unit/cli_spec.rb

This change adds InSpec to the output of the `chef --version`
command since InSpec is properly app-bundled inside the DK
and is promoted as a component of the DK.

Add inspec to chef --version output

---

chef-dk.gemspec
spec/unit/policyfile/read_cookbook_for_compat_mode_upload_spec.rb
spec/unit/policyfile_lock_install_spec.rb
spec/unit/policyfile_lock_validation_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb
spec/unit/policyfile_services/install_spec.rb

The SHAs all change because we're including more files in the cookbook
upload.

Move to Chef 13 compatibility

---

lib/chef-dk/skeletons/code_generator/recipes/template.rb

A typo in the template recipe inside the generator is preventing
the `chef generate template` command from working if the user
passes a content source with `-s`:
```
ChefDK::ChefConvergeError: Chef failed to converge: undefined method `context_source' for #<ChefDK::Generator::Context:0x007fb6e1d6d590>
```
The proper method name is `content_source`, not `context_source`.

Fix `chef generate template` with a content source

---

lib/chef-dk/command/generate.rb
lib/chef-dk/command/generator_commands/resource.rb
lib/chef-dk/skeletons/code_generator/recipes/resource.rb
lib/chef-dk/skeletons/code_generator/templates/default/resource.rb.erb
spec/unit/command/generator_commands/resource_spec.rb

We've been careful to talk only about custom Resources of late, and so
we should continue to do so in our tools.
This is a breaking change and will need to wait for chef-dk 2.0. cc @chef/maintainers

Rename LWRP to Resource

---

lib/chef-dk/command/update.rb
spec/unit/command/install_spec.rb
spec/unit/command/update_spec.rb

The install action was already doing this, just updates the update action to match.
* An "undefined method for nil" error when running `chef update` with a Chef Server or Artifactory source.
Signed-off-by: Jonathan Hartman <j@p4nt5.com>

Ensure a config object is passed down in the update action

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/cli.rb
lib/chef-dk/command/verify.rb
lib/chef-dk/commands_map.rb
spec/unit/command/verify_spec.rb

This both hides it from `--help` and shows a warning on stderr. Should help cut down on support requests. The plan outside of this is to refactor stuff such that `verify` will fail if you are airgapped or otherwise in a weird Ruby situation.

Make it clearer that chef verify is not for end users

---

appveyor.yml

defeats the purpose of our pinning rubygems.
and is currently bringing in a broken version of rubygems.

remove "update_rubygems" from appveyor.yml

---

lib/chef-dk/command/update.rb
lib/chef-dk/policyfile/solution_dependencies.rb
lib/chef-dk/policyfile_lock.rb
lib/chef-dk/policyfile_services/install.rb
spec/unit/command/update_spec.rb
spec/unit/policyfile/solution_dependencies_spec.rb
spec/unit/policyfile_demands_spec.rb
spec/unit/policyfile_lock_build_spec.rb
spec/unit/policyfile_services/update_spec.rb

rebase of #1185

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-config.json
spec/unit/command/generator_commands/cookbook_spec.rb

This modifies the default `config.json` in a generated cookbook to include cookstyle linting in the build cookbook.
Fixes #1146

Add cookstyle linting as default

---

omnibus/config/software/chef-dk.rb

not from the software dep
this fixes the multiple chef-config gem issue.

install ohai from Gemfile.lock instead of omnibus software dep

---

Gemfile
Gemfile.lock
chef-dk.gemspec

mostly pulls in chef 13.1.31 along with berkshelf-api-client 2.0.1 and the artifactory fix there.

bump deps, pins and more simplification

---

Gemfile.lock
omnibus/Gemfile
omnibus/Gemfile.lock
omnibus/config/projects/chefdk.rb
omnibus/config/software/chef-dk-env-customization.rb
omnibus/config/software/chef-dk-powershell-scripts.rb
omnibus/config/software/ruby-windows-system-libraries.rb
omnibus/config/software/rubygems-customization.rb

My suspicion is that the rust uninstall script accidentally clobbers
libgcc from embedded/bin, and that's why it's going AWOL. So this new
software project gets run as late as possible to put it back.

Ensure that necessary system libraries are installed

---

.expeditor/config.yml

Update the `.expeditor/config.yml` to use the new-style merge-action declaration syntax.
cc @schisamo @thommay @lamont-granquist

Use new Expeditor config format

---

lib/chef-dk/authenticated_http.rb
lib/chef-dk/command/diff.rb
lib/chef-dk/policyfile/chef_server_cookbook_source.rb
lib/chef-dk/policyfile/lister.rb
lib/chef-dk/policyfile_services/clean_policies.rb
lib/chef-dk/policyfile_services/clean_policy_cookbooks.rb
lib/chef-dk/policyfile_services/push.rb
lib/chef-dk/policyfile_services/push_archive.rb
lib/chef-dk/policyfile_services/rm_policy.rb
lib/chef-dk/policyfile_services/rm_policy_group.rb
lib/chef-dk/policyfile_services/show_policy.rb
lib/chef-dk/policyfile_services/undelete.rb
spec/unit/command/diff_spec.rb
spec/unit/policyfile/chef_server_cookbook_source_spec.rb
spec/unit/policyfile/comparison_base_spec.rb
spec/unit/policyfile/lister_spec.rb
spec/unit/policyfile/uploader_spec.rb
spec/unit/policyfile_evaluation_spec.rb
spec/unit/policyfile_services/clean_policies_spec.rb
spec/unit/policyfile_services/clean_policy_cookbooks_spec.rb
spec/unit/policyfile_services/push_archive_spec.rb
spec/unit/policyfile_services/push_spec.rb
spec/unit/policyfile_services/rm_policy_group_spec.rb
spec/unit/policyfile_services/rm_policy_spec.rb
spec/unit/policyfile_services/show_policy_spec.rb
spec/unit/policyfile_services/undelete_spec.rb

When pushing policies, we need to ensure that we send a cookbook that
the server can cope with, rather than just always the latest. To that
end, we'll use Chef::ServerAPI which has negotiation built in, rather
than our own API Client

Ensure we do protocol version negotiation

---

omnibus/config/projects/chefdk.rb

The cert has been updated as the old one expires on 2017-07-25. The new cert has also been deployed to our build infrastructure. 

Update SHA1 fingerprint for MSI signing cert

---

.expeditor/update_version.sh

There is a [bug](https://github.com/bundler/bundler/issues/5644) that is preventing us from updating the chef-dk gem via `bundle update` or `bundle lock --update`.
Until that is addressed, let's replace the version using sed.
Failure to automatically bump the version.

Update Gemfile.lock using sed rather than bundler

---

RELEASE_NOTES.md
tasks/announce.rb
tasks/templates/prerelease.md.erb
tasks/templates/release.md.erb

bumps RELEASE_NOTES to 1.6.1 since that is what was actually released.  goes back to three digit versions in the templates.

administrivia from chef-dk 1.6.1 release

---

README.md

The Chefspec link was a 404 since we moved the org.

Fix a few readme links

---

omnibus_overrides.rb

http://blog.rubygems.org/2017/08/27/2.6.13-released.html

Upgrade to Rubygems 2.6.13 to resolve CVEs

---

lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/.kitchen.yml
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

As of bento release [201708.22.0](https://github.com/chef/bento/blob/master/CHANGELOG.md#201708220-2017-08-22) there are now major version slugs for platforms with rolling/point release versioning across the board. kitchen-vagrant already automatically looks for matching boxes so only the generator needs to be changed and this is fully backward compatible.
For example:
`centos-7` -> `centos-7.3`
Signed-off-by: Seth Thomas <sthomas@chef.io>

Now that bento ships major version slugs, let's use them

---

lib/chef-dk/skeletons/code_generator/files/default/delivery-config.json
spec/unit/command/generator_commands/cookbook_spec.rb

The previous JSON was incorrect and would not actually enable cookstyle.

Update config.json with proper cookstyle use

---

omnibus/config/projects/chefdk.rb

This requires us to ensure that we run the correct gem binary during
omnibus builds

Upgrade to rubygems 2.6.13

---

lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Generates a LICENSE file based on the license chosen by the generator. Chooses template based on a valid license command argument input. Since this is enforced, we're good

Added LICENSE generation to skeleton

---

Gemfile
Gemfile.lock

Add the latest and greatest for the next ChefDK release.

Ship Chef 13.4.19

---

omnibus/config/software/chef-dk.rb

`berkshelf` no longer has a guard group in the gemfile so remove that exclusion
`chef` no longer has a changelog group so remove that exclusion
`foodcritic` has no changelog group, but it does have a development group: ronn, pry
`test-kitchen` (master currently) has a debug group and a docs group: yard, pry, pry-byebug, and pry-stack_explorer
`inspec` no longer has a changelog group, but it does have deploy, tools, and maintenance groups: pry, rb-readline, license_finder, tomlrb, octokit, netrc, and inquirer

Be more selective about what dev gems we bundle

---

CONTRIBUTING.md

Signed-off-by: Robert Miesen <robert.miesen@gmail.com>
I documented a possible mechanism for running the version of chef under active development discovered during the Seattle developer's summit.
None.

Documented how to run a version of chef-dk under development

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb

This changes the `chef generate cookbook` command to generate baseline tests for the CentOS 7.4.170 platform that is included by the default generate .kitchen.yml file. I also stripped out a/an articles from the generated contexts.
None

Add CentOS Platform to unit tests generated by `chef generate cookbook`

---

lib/chef-dk/generator.rb

When I use the `chef generate cookbook` command and pass it a license `--license 'apachev2'` the resulting files fail a rubocop pass off the bat due to the file having an addtitional blankline in the following files.
```
recipes/default.rb:18:1: C: Layout/TrailingBlankLines: 1 trailing blank lines detected.
spec/unit/recipes/default_spec.rb:19:1: C: Layout/EmptyLines: Extra blank line detected.
```
This PR strips the trailing `\n` from the `result` variable.
I only noticed this today and haven't created an issue, happy to create one if you like
~~- [ ] New functionality includes tests~~
~~- [ ] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)~~

Remove trailing newline

---

Gemfile
Gemfile.lock

- bumps and pins chef-provisioning-fog to version that supports
cheffish >= 13.0 (actually requires >= 13.1.0 because of bugfixes
it needs that went into that version).
- prior releases of ChefDK 2.x had as far as I know completely
broken chef-provisioning-fog since bundler was helpfully finding
very old versions that had no cheffish pin at all.
- floor of chef-provisioning-fog is pinned to address that issue
- the fog gem is no longer included, which removes swaths of fog
gems which were completely useless other than to cause dep
conflicts.  users which need to use support from the fog gem
must now `chef gem install fog` by hand.
- fog-aws is removed, users should use chef-provisioning-aws or
(discouraged) `chef gem install fog-aws` by hand.
- fog-google is still a mess and essentially …

bump+pin chef-provisioning-fog, bump deps

---

Gemfile
Gemfile.lock

- kitchen-google
- kitchen-digitalocean
- knife-google
- knife-ec2
it also does some additional bumps of the floors to prevent the
depsolver from ever getting too smart for its own good.
replaces #1429

bring in more gems to the chef-dk bundle

---

omnibus/Gemfile.lock
omnibus_overrides.rb

Both libxml2 and libxslt have CVEs in the previous releases. This syncs us with the versions in chef/chef.

Bump bundler, libxml2, libxslt and libyaml to the latest

---

Gemfile.lock
RELEASE_NOTES.md
lib/chef-dk/configurable.rb
lib/chef-dk/policyfile/cookbook_location_specification.rb
spec/unit/configurable_spec.rb
spec/unit/policyfile/cookbook_location_specification_spec.rb

Enables use of `chef_server_artifact` cookbook sources as recently implemented in cookbook-omnifetch
Includes https://github.com/chef/cookbook-omnifetch/pull/20 via cookbook-omnifetch 0.8.

Cookbook artifact source

---

omnibus/Gemfile.lock
omnibus_overrides.rb

openssl:
CVE-2017-3736 (OpenSSL advisory)  [Moderate severity] 2nd November 2017:
There is a carry propagating bug in the x86_64 Montgomery squaring procedure. No EC algorithms are affected. Analysis suggests that attacks against RSA and DSA as a result of this defect would be very difficult to perform and are not believed likely. Attacks against DH are considered just feasible (although very difficult) because most of the work necessary to deduce information about a private key may be performed offline. The amount of resources required for such an attack would be very significant and likely only accessible to a limited number of attackers. An attacker would additionally need online access to an unpatched system using the target private key in a scenario with persistent DH parameters and …

Bump openssl and rubygems to latest

---

Gemfile.lock

There was a pretty large regression introduced in 12.2 that I had to
push a fix out for. I noticed it thanks to ChefDK current testing out
cookbooks so the process worked, even though it's PR loud.

Pull in Foodcritic 12.2.1

---

RELEASE_NOTES.md
lib/chef-dk/command/update.rb
lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/attribute_merge_checker.rb
lib/chef-dk/policyfile/chef_server_lock_fetcher.rb
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/policyfile/included_policies_cookbook_source.rb
lib/chef-dk/policyfile/local_lock_fetcher.rb
lib/chef-dk/policyfile/lock_applier.rb
lib/chef-dk/policyfile/null_cookbook_source.rb
lib/chef-dk/policyfile/policyfile_location_specification.rb
lib/chef-dk/policyfile_compiler.rb
lib/chef-dk/policyfile_lock.rb
lib/chef-dk/policyfile_services/install.rb
lib/chef-dk/policyfile_services/update_attributes.rb
spec/unit/command/update_spec.rb
spec/unit/policyfile/attribute_merge_checker_spec.rb
spec/unit/policyfile/chef_server_lock_fetcher_spec.rb
spec/unit/policyfile/included_policies_cookbook_source_spec.rb
spec/unit/policyfile/local_lock_fetcher_spec.rb
spec/unit/policyfile/lock_applier_spec.rb
spec/unit/policyfile_demands_spec.rb
spec/unit/policyfile_includes_dsl_spec.rb
spec/unit/policyfile_includes_spec.rb
spec/unit/policyfile_install_with_includes_spec.rb
spec/unit/policyfile_lock_build_spec.rb
spec/unit/policyfile_services/update_attributes_spec.rb

Implements [rfc097](https://github.com/chef/chef-rfc/pull/280)
This adds `include_policy` to the dsl, allowing the ability to specify
a lock file to include. It currently supports `:path` and `:server` as a location
specification.
Example usage:
```ruby
include_policy "motd", path: "./motd.lock.json"
```
Things that work:
- Merging of cookbook dependencies works
- Detecting cookbook conflicts
- Merging of run lists
- Merging of named run lists
- Merging of attributes
- Detecting conflicting attributes
- Fetching locks from a chef server
Things that are not implemented:
- Fetching policies from git
Things that aren't great:
- No way to specify we want to update just a policy
- The error message you get from conflicting cookbooks tells you that
the source is a user defined dependency …

Add support for multiple policy files

---

lib/chef-dk/command/update.rb

Granular updates have been supported since 2.0.14. Updating the command
help to reflect current capabilities and behaviour

Update `chef` command help for granular updates

---

RELEASE_NOTES.md
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/recipe.rb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/recipe_spec.rb

The tests now live in an `integration` directory instead of a `smoke` directory.

They are integration tests, not smoke tests

---

lib/chef-dk/skeletons/code_generator/templates/default/build_cookbook/metadata.rb.erb
lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb
spec/unit/command/generator_commands/build_cookbook_spec.rb

Require Chef 12.14+ in the skeleton cookbook 

---

lib/chef-dk/policyfile/local_lock_fetcher.rb
spec/unit/policyfile/local_lock_fetcher_spec.rb

Fixes a bug where including a policy with a relative path would fail because it was not validating the correct file existed.

Fix bug causing relative paths to not work correctly in local_lock_fetcher

---

Gemfile.lock
chef-dk.gemspec

Signed-off-by: Sean Zachariasen <thewyzard@hotmail.com>
Updates minitar version to `~> 0.6` to allow version 0.6.1
* chef-dk, itself, depends on minitar.  Updating does not introduce test failures in rspec.
* berkshelf also depends on minitar, but has been passing their own tests with 0.6.1
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10173

update minitar dependency

---

lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb

Signed-off-by: Daniel DeLeo <dan@chef.io>
The `policyfile_zero` provisioner was deprecated long ago so it should be removed from the generator.
We could probably unify the policyfile/berks kitchen templates with a bit more work but it would take me a while to load everything back into my brain to do it.

Remove policyfile_zero provisioner

---

lib/chef-dk/skeletons/code_generator/files/default/chefignore

This isn't something we advocate for and it doesn't make much sense for us to ship it. Also remove the maintainers.toml file since only we were doing that and we've removed them all.

Remove strainer from the generated chefignore file

---

lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/attributes/default.rb

Fix link in example cookbook to point to the correct docs site URL

---

lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb

Signed-off-by: Franklin Webber <franklin@chef.io>
The chef recipe generator creates a recipe file and a matching spec file. This spec file should be named after the recipe it is spec'ing.

Fixes the spec file as it should display the recipe name and not default

---

.gitattributes
appveyor.yml
appveyor_registry.reg
omnibus/resources/chefdk/msi/source.wxs.erb

This change incorporates the Appveyor CI and installer changes that are present in https://github.com/chef/chef/pull/6941 so that ChefDK users on Windows will be able to use powershell_exec locally on their workstations via Chef Client if they so choose.
These files are required to be duplicated to the chef-dk project because installer source files are maintained separately for each project.

powershell_exec mixin support for ChefDK MSI installer

---

omnibus/resources/chefdk/msi/source.wxs.erb

Chef DK also suffers from the same issue as https://github.com/chef/chef/issues/7103 where the zip file does not unzip in the case of MSI repair.  This PR fixes that.
Signed-off-by: Stuart Preston <stuart@chef.io>

Attempt to unzip files if MSI repair selected

---

omnibus/Gemfile
omnibus/Gemfile.lock
omnibus/config/software/chef-dk.rb

the appbundler invocation here is slightly odd now that I look at it,
but its necessary.  this is the way to properly do the ChefDK magic.
tested in CI

get omnibus tracking back on master

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/CHANGELOG.md.erb
spec/unit/command/generator_commands/cookbook_spec.rb

Generates a `CHANGELOG.md` for each cookbook when using the default generator.
Inspired by [this question on discourse](https://discourse.chef.io/t/cookbook-changelog-rb/12984/1).
Signed-off-by: Nathen Harvey <nharvey@chef.io>

Generate a `CHANGELOG.md` for cookbooks

---

omnibus/resources/chefdk/msi/localization-en-us.wxl.erb

The Custom Setup dialog was displaying its title and description text to the default black for font color. Set it to white here, so that the text is legible on the dark banner background.
Example of the hard-to-read dark text:

set windows installer custom setup font to white

---

Rakefile
lib/chef-dk/cookbook_profiler/git.rb
lib/chef-dk/exceptions.rb
lib/chef-dk/policyfile/chef_server_lock_fetcher.rb
lib/chef-dk/policyfile/git_lock_fetcher.rb
lib/chef-dk/policyfile/local_lock_fetcher.rb
lib/chef-dk/policyfile/policyfile_location_specification.rb
lib/chef-dk/policyfile/source_uri.rb
lib/chef-dk/policyfile/storage_config.rb
omnibus/config/software/chef-dk.rb
spec/unit/policyfile/git_lock_fetcher_spec.rb

This completes the specification as defined by RFC-097 by adding Git support for Policyfile Includes.
Example Usage:
```
name 'delightful_policy'
default_source :supermarket
run_list 'delightful_example::default'
include_policy 'base_policy',
git: 'https://github.com/happycustomer/chef-repo.git',
branch: master,
path: 'cookbooks/base/Policyfile.lock.json'
cookbook 'delightful_example', path: './'
```
- Implements [RFC-097](https://github.com/chef/chef-rfc/blob/master/rfc097-policyfile-includes.md)
- Fixes [SUSTAIN-897]
- Internal issue SUSTAIN-897

Add Git support for include_policy.

---

.expeditor/config.yml
habitat/plan.sh

publish habitat packages

---

.expeditor/config.yml
habitat/plan.sh

Signed-off-by: Jon Cowie <jonlives@gmail.com>
This fixes the habitat plan to look for the correct gemspec file (it's called chef-dk.gemspec)

Fix hab plan to use correct gemspec name

---

Gemfile.lock
omnibus/Gemfile.lock

mixlib-config adds the is_default? method
mixlib-install properly detects Amazon Linux 2

Update mixlib-config / mixlib-install

---

Gemfile
Gemfile.lock

Update to Chef 14.3.37

---

habitat/plan.ps1

This will replace the plan that is currently maintained in [core-plans](https://github.com/habitat-sh/core-plans). Unlike the bash plan, this plan does not build from source but grabs the specified version from the packages site instead.

add windows habitat plan

---

Gemfile
Gemfile.lock
lib/chef-dk/command/verify.rb
omnibus/config/software/chef-dk.rb
spec/unit/command/verify_spec.rb

ChefDK holds all the logic for the massive dependency resolution task.
Because of this we have to include Chef Apply as a gem dependency, even
though we only want to expose it via Chef Workstation and not Chef
Apply. That is why we do not appbundle it here but do appbundle it in
Chef Workstation.
As we move the dependency solving logic out of the ChefDK (per
https://github.com/chef/chef-rfc/pull/308) and seperate out components
(like policyfile and the 'chef' binary) we will eventually not need this
dependency here. But until that day...
SHACK-304

[SHACK-304] Add Chef Apply as a gem dependency

---

Gemfile.lock

```
Fetching chef-apply 0.1.18
Downloading chef-apply-0.1.18 revealed dependencies not in the API or the
lockfile (chef-dk (>= 3.0)).
Either installing with `--full-index` or running `bundle update chef-apply`
should fix the problem.
```
Hoping this fixes ☝️ 
SHACK-304

[SHACK-304] Habitat build fails with bundler error

---

.expeditor/update_version.sh
Gemfile.lock

Right now it also updates the chef-apply gem dependency, which causes
failures in the build pipeline. We want to leave that constraint alone.
See
https://github.com/chef/chef-dk/commit/a56aa76c07610c2e202bb845d6f2b6c01d1488fb
for an example of the error occuring.
SHACK-304

[SHACK-304] Expeditor version update needs to only update the ChefDK version

---

habitat/plan.sh

Pins ruby to 2.5.1 in the habitat build and updates the GEM_PATH for the revision.
Currently all of the app bundled binaries are broken by default because ruby 2.5.1 will meet the installation requirements but the plan expects 2.4.x.

Pin ruby to 2.5.1 in habitat plan

---

tasks/announce.rb
tasks/templates/prerelease.md.erb
tasks/templates/release.md.erb

This just doesn't make sense. I moved it over to chef/chef where it belongs.

Remove TK from the Announce Rake Task

---

chef-dk.gemspec

This way it shows up as Apache-2.0 on rubygems

Add missing license field to the Gemspec

---

README.md

Signed-off-by: Seth Thomas <sthomas@chef.io>
Adds badges for DockerHub so we can easily link to the images.
Fixes #1098

Add DockerHub badges

---

.expeditor/update_dep.sh
.expeditor/update_dockerfile.sh

Attempt to wait long enough for rubygems to have the gem we need.

Add a sleep to the dep updater in Expeditor

---

.expeditor/config.yml
.expeditor/update_chef.sh

When Chef is promoted to stable we want to update the Gemfile, pull in the new version, and then open a PR with that bump.

Automatically update Chef version when it's promoted

---

Gemfile
Gemfile.lock

Update mixlib-archive to resolve chdir issues with TK and Berkshelf.
#1663

Bump mixlib-archive to 0.4.16

---

.expeditor/update_chef.sh
.expeditor/update_dep.sh
ci/dependency_update.sh
tasks/dependencies.rb

we're calling scripts to call rake tasks to call scripts to call rake
tasks to mostly execute shellcodes. this gets rid of at least 2 levels
of indirection.

Simplify / fix rake task for updating gem dependencies

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/describe_cookbook.rb

Signed-off-by: Daniel DeLeo <dan@chef.io>
Adds a command that dumps the identifier data so users can figure out why a given cookbook has a given identifier. It often happens that somewhere in a Ci pipeline or between two developers laptops there is some mysterious difference between cookbooks that makes the identifier "flap." This should make it easier to understand what's going on.
I can't find the links but this comes up every so often in discourse and slack.

Add a command that can debug why a cookbook gets a given identifier

---

Gemfile.lock
omnibus/Gemfile.lock

This gives us metadata for all the new resources in Chef 14.3 / 14.4
@tyler-ball This should go in before the DK release so we have the latest metadata.

Update to Foodcritic 14.1.0

---

.expeditor/config.yml

Signed-off-by: Seth Thomas <sthomas@chef.io>
Update expeditor config to use subscriptions as artifact_actions is deprecated

Use subscriptions and fix expeditor warning

---

lib/chef-dk/policyfile/uploader.rb
spec/unit/policyfile/uploader_spec.rb

The goal of this change is to surface more information so that it's
easier for users to detect a certain class of mistakes (e.g., run
`chef push` from the wrong working directory) and to produce a more
useful log of what `chef push` did when run in a Ci context.
Possible downside is that the extra information may be offputting to
novice users, but that's probably a wash as some novices would likely
appreciate the additional detail about the consequences of the command
they are running.
```
Uploading policy to policy group new_pgroup
< other stuff >
```
```
Uploading policy jenkins (d064016951) to policy group new_pgroup
< other stuff >
```
Inspired by a debugging session in Chef Software internal slack.

Include more information about the policy in `chef push` output

---

Gemfile
Gemfile.lock

Require at least 3.4.1 since 3.4.0 is broken for appbundling

Update chef-vault to 3.4.1

---

RELEASE_NOTES.md
lib/chef-dk/command/update.rb
lib/chef-dk/policyfile_services/install.rb
spec/unit/policyfile_services/update_spec.rb

This option has two possible values for now:
- 'relaxed' (default value). This is the behavior before this patch.
`chef update Policyfile.rb apache2` will upgrade apache2 and all its
dependencies
- 'strict'. This behavior is very strict: it updates only the cookbook(s)
mentionned in the command line.
The intent of this patch is to pave a possible way to have a third
strategy who would upgrade cookbooks mentionned on the command line to
their maximum existing version (possibly by upgrading other cookbooks if
necessary).
This patch already gives very fine control to users who want to update a
single cookbook (or a few cookbooks only).

Add new option update-strategy for policy updates

---

RELEASE_NOTES.md

A greater understanding of what is being released in ChefDK 3.3.
No existing, numbered issues, but does attempt resolve the amorphous problem of communicating change.
-  ~New functionality includes tests~ Is markdown testable?
- ~All tests pass~ See above.

add release notes for 3.3

---

omnibus/.gitignore
omnibus/.kitchen.vmware.yml
omnibus/Berksfile
omnibus/README.md
omnibus/files/openssl-customization/windows/ssl_env_hack.rb
omnibus/kitchen.yml

This syncs a good portion of the omnibus kitchen config to match that now in chef-client. It modernizes the kitchen config and uses boxes that match what we actually ship.

Update omnibus kitchen config to match chef-client

---

Dockerfile

Delete logs and file backups in the Docker image

---

.expeditor/config.yml

This PR enables Habitat package builds of chef-dk for the x86_64-linux-kernel2 PackageTarget. 
Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>

Enable x86_64-linux-kernel2 habitat builds for chef-dk

---

.expeditor/config.yml

This fixes the https://expeditor.chef.io/docs/reference/status-checks/#config-006
error we are seeing now.
N/A

Fixing expeditor subscriptions to listen to proper events

---

omnibus/config/projects/chefdk.rb

This should unbreak the build.

Switch from chef-cleanup to ruby-cleanup definition

---

Gemfile
Gemfile.lock

The UTF16 changes seem to have broken things.

Pin winrm to 2.2.3 to prevent Test Kitchen failures

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Signed-off-by: Seth Thomas <sthomas@chef.io>
☝️ 
~- [ ] New functionality includes tests~
~- [ ] All tests pass~
~- [ ] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)~

Removing winrm pin

---

Dockerfile

Allows the `kitchen-dokken` to be used in CI pipelines without modification.  Typically you have to install rsync to make it work.
E.g. for Gitlab CI
```
image: chef/chefdk:current
variables:
DOCKER_HOST: tcp://docker:2375
services:
- docker:dind
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version
- apt-get update && apt-get install rsync -y
```

Add rsync to docker image to support kitchen-dokken

---

Dockerfile

Added graphviz to docker to make `berkz viz` available
- ~New functionality includes tests~
- ~RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)~

Add graphviz to docker image to support berks viz

---

.expeditor/update_dep.sh

120 seconds does not seem to be enough time for Rubygems to actually
publish the gem so it can be downloaded.
N/A

Increase expeditor dependency update timeout

---

lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_dokken.yml.erb

To provide support out-of-the-box for `kitchen-dokken` there is a flag now to specify which base kitchen configuration to use.
> By default a chef cookbook will generate a kitchen configuration using vagrant as the driver. You may find that you want to use `kitchen-dokken` as your default kitchen environment when generating your cookbooks. 
>
>     $ chef generate cookbook COOKBOOKNAME --kitchen dokken
>
> That plugin requires a little more setup as it is a `driver`, `provisioner`, and `transport`. It also requires special considerations with the platforms that it uses for testing.
>
> To learn more about the benefits of `kitchen-dokken` take a look at this blog post: https://blog.chef.io/2018/03/06/kitchen-docker-or-kitchen-dokken-using-test-kitchen-and-docker-for-fast-cookbook-testing/ …

Adds a kitchen flag that gives options for different kitchen configs

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Rake is being included out of the box with our ruby install and then we
install the latest. This results in double rake. If we pin we can avoid
that. We'll need to adjust this pin when we bump to 2.6 but it works
great in 2.5.3.

Prevent rake from being packaged twice in DK

---

Gemfile
Gemfile.lock

These are shipped by our Ruby install and then we install newer
releases. We need to stop doing this by pinning to the version that
comes in our source.

Prevent shipping two copies of rdoc and minitest gems

---

chef-dk.gemspec

The omnibus_overrides is used to build the omnibus package and shouldn't
be needed in a release artifact. We also don't need a readme buried deep
in a ruby gems dir on the filesystem.

Don't ship omnibus_overrides or readme in the gemfile

---

Rakefile

This keeps someone from running rake release on accident.

Remove the Rake gemtasks since we use expeditor

---

habitat/plan.sh

We don't include the rubygems tasks anymore so just do it by hand. Also make sure we setup chef-resource-inspector as a binary.

Fix the habitat plan to not use rake install

---

.expeditor/config.yml
Gemfile.lock
omnibus/Gemfile.lock

Reduce the install size by bumping mixlib-log and mixlib-config. Also bump to the latest nokogiri, which fixes a regression in 1.9.0

Update mixlib-config, mixlib-log, and nokogiri to reduce install size

---

Gemfile.lock
omnibus/Gemfile.lock

Update mixlib-versioning to 1.2.7 to slim the install size

---

omnibus/Gemfile.lock

This will allow the new inspec deps to pass

Bump license_scout to 1.0.20 for licensing tests

---

RELEASE_NOTES.md

Forgot these before releasing, backfilling before minor version bump

Adding release notes for 3.6 release

---

omnibus/config/software/chef-dk.rb
omnibus/config/software/git-custom-bindir.rb

Remove AIX/Solaris bits since workstation / DK will never run on AIX. I'm removing these from the upstream git definition as well since they're only necessary for old versions of git we shouldn't be supporting.
Use --no-document which is required for Ruby 2.6. This gets us ready to support Ruby 2.6.

Cleanup the omnibus definition for DK

---

.expeditor/update_dep.sh
.github/CODEOWNERS

Something changed with our expeditor build image. Now if we only
'gem install rake' we are missing both dependend gems and local code
paths. Running rake in the scope of 'bundle' should fix this.
N/A

Missing required gems for rake to run tasks

---

.expeditor/config.yml

This change ensures we are promoting our Hab packages to `current` and
`stable` at the same time we execute said promotions for the Omnibus
packages.

Promote Hab package alongside Omnibus package

---

lib/chef-dk/command/provision.rb
spec/unit/command/provision_spec.rb

It will be removed in ChefDK 4. See
https://github.com/chef/chef-dk/pull/1614
N/A

Deprecating the 'chef provision' command

---

omnibus_overrides.rb

Upgrading rubygems to 3.0.2 failed tests on all Unix platforms so pinning it back to 2.7.7
Tests pass on all platforms after pinning back

Rubygems pin back to 2.7.7

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

7.0 is out, but this is for the next major DK release

Update Fauxhai to 6.11 and lock it there

---

habitat/plan.sh

Hab now has ruby version 2.5.3 in core. Lets use that since it matches our omnibus version.
Build failure

Update hab ruby to 2.5.3

---

Gemfile
Gemfile.lock

rbnacl 6.x no longer supports rbnacl-libsodium

pin rbnacl to 5.x

---

lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_test.rb.erb

FWIW, I think this line can be removed entirely...but not 100% sure.

Fix `# # encoding` in cookbook generator

---

.bldr.toml
.expeditor/build.habitat.yml
.expeditor/config.yml

_This is a release engineering only change._
Update Expeditor configuration to use new Buildkite-based Habitat builds.

Leverage new Buildkite-based Hab builds

---

.expeditor/config.yml
Gemfile
Gemfile.lock
chef-dk.gemspec
omnibus/Gemfile.lock
omnibus_overrides.rb

We have working Ruby 2.6 builds in omnibus-software now. This bumps DK up.

Update Ruby to 2.6 and Rubygems to 3.0.3

---

.travis.yml
Gemfile
Gemfile.lock
appveyor.yml
omnibus/Gemfile.lock

Remove some branch mess in travis/appveyor, prevented the new kitchen-ec2 plugin from coming in, and bumped the world.

Bring in Chef 14.12.9 and other newer deps

---

Gemfile.lock
habitat/plan.sh
omnibus/Gemfile.lock
omnibus/config/software/chef-dk.rb

This gets us a working inspec binary with InSpec 4.0.

Appbundler inspec-bin not inspec

---

lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/README.md
lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/kitchen.yml
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_dokken.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb
spec/unit/command/generator_commands/cookbook_spec.rb

We should auto generate cookbooks testing Ubuntu 18.04 not 16.04.

Update cookbook templates to use Ubuntu 18.04

---

.expeditor/config.yml
Gemfile.lock
tasks/dependencies.rb

This prevents our expeditor subscriptions from updating the lock file to Bundler 2.x which breaks the builds.

Fix the dep bumping rake task to work with the correct bundler

---

lib/chef-dk/command/describe_cookbook.rb

`describe-cookbook` should consider cookbooks with a metadata.json file as a valid cookbook.

Fix describe-cookbook to support cookbooks with metadata.json

---

omnibus/config/projects/chefdk.rb

The resulting distribuions are licensed under the Chef EULA.
Signed-off-by: Bryan McLellan <btm@loftninjas.org>

Update the omnibus build license to the Chef EULA

---

README.md
tasks/dependencies.rb

In accordance with https://github.com/chef/chef-oss-practices/blob/master/repo-management/repo-states.md
* update README with project state and response times
Bonus trailing whitespace removal to appease chefstyle.

update repo to new Chef OSS practices

---

README.md
lib/chef-dk/command/generate.rb
lib/chef-dk/policyfile_services/export_repo.rb
lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/README.md
lib/chef-dk/skeletons/code_generator/files/default/chefignore
lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb

Add code of conduct files to the chefignore so these don't go up to the server
Replace Delivery with Workflow in a few places
Take the prototype bit out of the Delivery local mode file comments
Chef Client -> Chef Infra Client in more places

More branding fixes + generator improvements

---

.travis.yml
RELEASE_NOTES.md
lib/chef-dk/command/generator_commands/cookbook.rb
lib/chef-dk/skeletons/code_generator/files/default/cookbook_readmes/README.md
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook_file.rb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
spec/unit/command/generator_commands/cookbook_file_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Generate cookbooks with policyfiles by default

---

RELEASE_NOTES.md
lib/chef-dk/command/generator_commands/repo.rb
lib/chef-dk/skeletons/code_generator/recipes/repo.rb

This matches the behavior of chef generate cookbook. We should probably just get verbose pushed up into generate itself and utilize it there, but this achieves the desired user experience of not seeing 2 pages of chef run when all you want is to know if the repo was generated.

Make chef generate repo quiet by default

---

lib/chef-dk/command/shell_init.rb
lib/chef-dk/policyfile_services/push_archive.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/dot-chef-repo.txt
lib/chef-dk/skeletons/code_generator/templates/default/Policyfile.rb.erb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/policyfile_spec.rb
spec/unit/command/generator_commands/repo_spec.rb
spec/unit/policyfile_services/push_archive_spec.rb

These commands run in Workstation, which is a bit confusing when everything says DK all over. We should probably use our own dist file concept to get around this, but this makes things more generic, which works for now.

Update command help / contents to make sense in Workstation

---

lib/chef-dk/command/generator_commands/chef_exts/generator_desc_resource.rb
spec/unit/command/generator_commands/chef_exts/generator_desc_resource_spec.rb

This was very Chef < 12.5 and needed some love.

Modernize the chef resource used to log during generate commands

---

omnibus_overrides.rb

Otherwise we have 1.17.2 and 1.17.3 and that introduces extreme performance issues.

Prevent double bundler by pinning to 1.17.2

---

Gemfile.lock

I accidentally bumped this in my last PR

Revert the Gemfile.lock back to 1.17.3

---

lib/chef-dk/policyfile/chef_server_lock_fetcher.rb
lib/chef-dk/policyfile/local_lock_fetcher.rb
lib/chef-dk/policyfile/lock_fetcher_mixin.rb
lib/chef-dk/policyfile/policyfile_location_specification.rb
lib/chef-dk/policyfile/remote_lock_fetcher.rb
spec/unit/policyfile/local_lock_fetcher_spec.rb
spec/unit/policyfile/lock_fetcher_mixin_spec.rb
spec/unit/policyfile/remote_lock_fetcher_spec.rb
spec/unit/policyfile_includes_dsl_spec.rb

Addresses https://github.com/chef/chef-rfc/pull/333 by adding support for include_policy with remote sources and adds support and validation for policy_revision_id with path and remote include_policy.
https://github.com/chef/chef-rfc/pull/333
Updated unit tests and applied chefstyle.

RFC097 include_policy with remote sources and validating policy_revision_id with path

---

.expeditor/update_chef.sh
Gemfile
Gemfile.lock
lib/chef-dk/command/verify.rb
omnibus/config/software/chef-dk.rb

Add chef-bin dependency

---

Gemfile
Gemfile.lock
lib/chef-dk/command/verify.rb

Also accept the license for chef-apply in the verify command.

Update Chef Infra Client to 15.0.300

---

lib/chef-dk/command/verify.rb
lib/chef-dk/component_test.rb

Set it in the default environment variables so future tests don't need
any special change to work.
Windows pipeline failures

'chef verify' strips all the environment so add CHEF_LICENSE back

---

.expeditor/config.yml
RELEASE_NOTES.md

* Adds a note about `knife bootstrap` cloud providers not working until we update the associated gems, will happen in 4.1
* Fix out expeditor config so we can successfully `/expeditor promote`
N/A

ChefDK 4.x Release notes prep for promotion to stable

---

lib/chef-dk/command/shell_init.rb

The shell tries to execute the error message 'you cannot run without
accepting the license...' and it is very non-intuitive for users.
N/A

Do not request license when users shell-init

---

Gemfile.lock
omnibus/Gemfile.lock

Pull in the latest dokken and omnibus-software as well

Update kitchen-dokken to 2.7

---

README.md

We don't need too support a Mac release from 2015.

Remove legacy macOS uninstall instructions

---

habitat/plan.sh

This fixes failures in the hab package

Update Ruby in the hab plan to 2.5.5

---

habitat/plan.sh

Use the correct Ruby release and include libarchive.

Fix hab builds of ChefDK

---

omnibus/config/software/git-custom-bindir.rb

This just came over when we copied the git def

Remove some AIX code from our omnibus def

---

.expeditor/release.omnibus.yml

Ubuntu 14.04 is EOL and we should stop building / testing packages for
it. Instead we'll build on Ubuntu 16.04 and test those packages on 16.04
and 18.04.

Remove Ubuntu 14.04 from the build pipeline

---

omnibus/omnibus-test.ps1
omnibus/omnibus-test.sh

This just updates the `omnibus-test.*` scripts to use tools that have been moved into the omnibus-toolchain. It also makes some changes to output to be more consistent across our omnibus projects.

[chefdk-3] Use new omnibus-toolchain scripts in omnibus-test.* scripts

---

lib/chef-dk/cli.rb
spec/unit/cli_spec.rb

1) Remove delivery and berkshelf from the output as we care less about these tools
2) Include cookstyle and foodcritic as we do care what versions we're running
3) Output the branding name not the CLI name
Old output:
```
Chef Development Kit Version: 4.0.75
chef-client version: 15.0.300
delivery version: 0.0.52 (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 2.2.5
inspec version: 4.6.4
```
New output:
```
Chef Development Kit Version: 4.0.75
Chef Infra Client version: 15.0.300
Test Kitchen version: 2.2.5
Foodcritic version: 16.0.0
Cookstyle version: 4.0.0
InSpec version: 4.6.4
```

Improve chef --version command

---

habitat/plan.sh

1) we don't use iconv in chef/chef so why use it here
2) we needed pkg-config, which is recommended on the nokogiri site

Fix habitat packages that didn't build

---

lib/chef-dk/component_test.rb

We're never going to support Solaris. Let's not bother checking if we're on Solaris.

Remove Solaris support from the component_check code

---

README.md
lib/chef-dk/dist.rb
spec/unit/cli_spec.rb
spec/unit/command/base_spec.rb
spec/unit/command/generator_commands/generator_generator_spec.rb
warning.txt

Use the same name for this project everywhere.

Refer to the product as ChefDK to match docs + downloads

---

lib/chef-dk/command/verify.rb

-v exits with 2, which causes the builds to fail

Verify foodcritic with --list not -v

---

Gemfile
Gemfile.lock

This already comes in via cookstyle so this is basically just simplifying our gemfile/lock.

Remove explicit dependency on rubocop

---

RELEASE_NOTES.md

Start the DK 4.1 release notes.

Add the DK 4.1 Release Notes

---

Gemfile
Gemfile.lock

The next released version of chef-run (chef-apply) , 0.3.3, pulls in the ChefCLI library.
This doesn't belong in ChefDK since ChefCLI is a fork of DK's libraries
for future Workstation development, so we'll pin to 0.3.0 

Lock chef-apply to =0.3.0

---

omnibus/Gemfile.lock
omnibus_overrides.rb

There's nothing important in this release other than a few minor bugfixes. The other alternative was to roll bundler forward to 1.17.3 so that the embedded rubygems bundler matched, but this meant we had bundler 1.17.2 built into ruby 2.6.3 and then 1.17.3 installed on top of that. There's little value in that and it bloats our package size. Let's not do that unless there's a critical bug or CVE we need in rubygems / bundler.
This also bumps omnibus-software to include the new ruby cleanup def that fails if we have double bundler and the new rubygems def that removes the rubygems-update gem once rubygems is installed.

Roll back rubygems to 3.0.3 to prevent double bundler

---

Gemfile
Gemfile.lock

ChefSpec 8 and later pull in ChefCLI, which is a fork of
the ChefDK gem. In order to avoid pulling ChefCLI into ChefDK,
we'll pin chefspec to < 8.

pin chefspec to < 8

---

RELEASE_NOTES.md

Right now this is 4.1.18, but it may become 4.2.0.

Add release notes for the next DK

---

lib/chef-dk/builtin_commands.rb

This should be a valid command since we have a class for it. The class throws the friendly warning let folks know it's deprecated

Fix deprecated chef provision command to not fail

---

README.md
lib/chef-dk/command/verify.rb
omnibus/config/projects/chefdk.rb
omnibus/package-scripts/chefdk/postinst

The installer and add/remove program name were all branded as Chef Development Kit. We've changed all the docs site and other references. This unifies it all on ChefDK.

Remove the last mentions of Chef Development Kit

---

.expeditor/release.omnibus.yml

This will get us a Windows 2019 build on the downloads site.

Add Windows 2019 build verification

---

omnibus/Gemfile
omnibus/Gemfile.lock

This change only affects CI. A new version of omnibus is required and the artifactory gem is required for the publish part of the build stage.
https://github.com/chef/omnibus-buildkite-plugin/issues/22

[ci] Add artifactory to omnibus gemfile

---

.expeditor/verify.pipeline.yml
.gitignore
.studiorc
habitat/plan.sh
habitat/scripts/ci_integration_tests.sh
habitat/tests.sh

Improvements to the way we package Chef-DK with Habitat (for Linux systems)
- Restructure `wrap_ruby_bin` to respect `DEBUG` env-var
- Restructure `do_install` to execute in a sub-shell
- Restructure `do_build` to execute in a sub-shell
- Use `SRC_PATH` instead of `PLAN_CONTEXT/..`
- Remove unnecessary `do_before` callback
- Use `pkg_interpreter_for` and remove `core/coreutils` dependency
- Makes `pkg_version` a func to use `update_pkg_version` 
- Adds buildtike job to test habitat package to prevent regressions
- Quick general styling
None

Improve packaging Chef-DK with Habitat

---

.expeditor/release.omnibus.yml

As of March 31st 2019, SLES 11 is no longer generally supported. Per our
support process we will no longer officially support SLES 11.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy

Stop building ChefDK on EOL SLES 11

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Also bump the minimum allowed version of inspec.

Update Chef Infra Client to 15.2

---

omnibus/config/projects/chefdk.rb

Begin signing MSI's with renewed Windows Signing Cert

---

.expeditor/release.omnibus.yml

As of March 31st 2019, SLES 11 is no longer generally supported. Per our
support process we will no longer officially support SLES 11.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy

Deprecate sles 11 for chefdk-3 branch

---

omnibus/config/software/git-custom-bindir.rb

Bump git for non-Windows hosts to 2.23.0

---

habitat/plan.sh
habitat/tests.sh
omnibus/config/software/chef-dk.rb

dco has a development dep on rspec-command which depends on
mixlib-shellout 2.x and we use 3.x in chef-client now. This is breaking
omnibus builds.

Appbundle DCO without the development gems

---

habitat/plan.sh

We have not been running Habitat builds for a while so we must have
missed a change to 'do_download'. Copying the pattern from Chef Infra
Client habitat package.
Backporting https://github.com/chef/chef-dk/pull/2277 to `chefdk-3` branch

Fix Habitat build failure

---

.expeditor/run_linux_tests.sh

The compression / upload is time consuming and costly.

Use a sha256 checksum file to avoid compressing / uploading one every run

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml

Remove a duplicate rspec test
Switch from bz2 for bundler caching to gz, which is faster to compress and decompress, but only takes up about 12% more space. Worth it for the speed up.

Further speed up our PR tests

---

.expeditor/verify.pipeline.yml
Gemfile.lock
RELEASE_NOTES.md
omnibus/Gemfile.lock

This is also tagged to bump the version to 4.5.0 so we can ship

Add ChefDK 4.4 and 4.5 release notes & bump Cookstyle

---

lib/chef-dk/policyfile/uploader.rb
lib/chef-dk/policyfile_services/rm_policy.rb
spec/unit/policyfile/uploader_spec.rb
spec/unit/policyfile_services/clean_policies_spec.rb
spec/unit/service_exception_inspectors/http_spec.rb

Using this results in spam to the console. This is really annoying during our tests.

Replace usage of deprecated Net::HTTPServerException error class

---

omnibus/Gemfile
omnibus/Gemfile.lock

Bring in newer deps by bumping license scout and loosening
mixlib-shellout

Update license scout dependency to unblock chef versions

---

omnibus/config/projects/chefdk.rb
omnibus/config/software/more-ruby-cleanup.rb

This will remove several thousands files in the DK installation, which speeds up install times on Windows.

Add the Ruby cleanup omnibus logic from Workstation

---

Gemfile
Gemfile.lock
habitat/plan.sh
lib/chef-dk/command/verify.rb
omnibus/config/software/chef-dk.rb
spec/unit/command/verify_spec.rb

This removes the chef-apply gem, which pulls in the `chef-run` binary.
`chef-run` only works in Workstation; we originally included it in DK
only because we had to in order to have the gem app-bundleable
in the DK-based Workstation build.
-[x] Chore (non-breaking change that does not add functionality or fix an issue)

Remove chef-run

---

omnibus/config/software/more-ruby-cleanup.rb

We use this in the DK gem post install and without this the tests fail

Make sure we don't cleanup warning.txt

---

.expeditor/verify.pipeline.yml
README.md
Rakefile
lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/README.md

De-emphasize Foodcritic as we've replaced it with Cookstyle

Remove Foodcritic tests / Foodcritic from the readme

---

.expeditor/buildkite/verify.ps1
omnibus_overrides.rb

We don't use either of these anymore

Remove references to Travis and Appveyor

---

omnibus/Gemfile.lock

I typo'd the location of the sync gem license file

Update license_scout to 1.1.3

---

.expeditor/release.omnibus.yml

Windows 2008 R2 is now officially EOL so we should no longer push builds
to downloads.chef.io

Remove Windows 2008 R2 from the build pipeline

---

omnibus/config/software/more-ruby-cleanup.rb

This should help shave a large chunk of the install

Perform the same artifact cleanup we do in workstation

---

.expeditor/release.omnibus.yml

Windows 2008 R2 is EOL as of 1/14/2020.

Stop producing Windows 2008 R2 builds

---

habitat/plan.sh
omnibus/config/software/chef-dk.rb

Due to pins in inspec vs. inspec-core in 4.18.51 we're getting failures.
This will be resolved with a new inspec release, but that doesn't
unblock us today.

Exclude omnibus_packages in chef bundle testing

---

omnibus/Gemfile.lock
omnibus/config/patches/rb-fsevent-gem.patch
omnibus/config/projects/chefdk.rb
omnibus/config/software/chef-dk.rb
omnibus/config/software/git-custom-bindir.rb
omnibus/config/software/rb-fsevent-gem.rb

This changes makes the neccessary changes to enable the pkg to pass Apple's notarization requirements.
1. Update omnibus and omnibus-software to versions that support deep signing
2. Drop 'Developer ID Installer:' from signing key. This lets sigining pick up the correct key for what is being signed.
3. Add bin_dirs and lib_dirs to chefdk and git-custom-bindir software definitions so siging can find their binaries and libraries.
4. Add software definition for rb-fsevent-gem so we build the gem. This resolves an issue where the shipped binary is build on to old an sdk.
5. Patch rb-fsevent-gem build to work in our environment. Set minimum target to current os and discover the sdk version.
https://github.com/chef/omnibus/pull/924 …

Fixes all notarization issues

---

Gemfile
Gemfile.lock

FFI is being more strict now and throwing deprecations. Pin until we can work around this.

Pin FFI to avoid warnings on Windows hosts when running knife

---

omnibus/Gemfile.lock
omnibus/resources/chefdk/pkg/entitlements.plist

ffi loads c code into memory in an unsigned way and this allows workstation
to work with the hardened runtime.

Adding entitlement for unsigned memory execution

---

omnibus/Gemfile.lock
omnibus/config/patches/rb-fsevent-gem.patch
omnibus/config/projects/chefdk.rb
omnibus/config/software/chef-dk.rb
omnibus/config/software/git-custom-bindir.rb
omnibus/config/software/rb-fsevent-gem.rb
omnibus/resources/chefdk/pkg/entitlements.plist

Fixes all notarization issues
This changes makes the neccessary changes to enable the pkg to pass apples notarization requirements.
1. Update omnibus and omnibus-software to versions that support deep signing
2. Drop 'Developer ID Installer:' from signing key. This lets sigining pick up the correct key for what is being signed.
3. Add bin_dirs and lib_dirs to chefdk and git-custom-bindir software definitions so siging can find their binaries and libraries.
4. Add software definition for rb-fsevent-gem so we build the gem. This resolves an issue where the shipped binary is build on to old an sdk.
5. Patch rb-fsevent-gem build to work in our environment. Set minimum target to current os and discover the sdk version.
6. Add unsigned memory execution entitlement because ffi loads c code into …

Adding notarization and entitlements for unsigned memory execution (backport from master)

---

.expeditor/release.omnibus.yml

We have Debian 10 verifiers now

Validate builds on Debian 10

---

lib/chef-dk/command/verify.rb

chefspec is failing verification because it's pulling `chef` from git
master.  I was not able to find any related changes in the repository or deps 
that would account for the change in behavior since the last good build in January,
but I do see thatby specifing a no-op `GEMFILE_MOD` we'll stick with the same
chef gem version that is in the gemspec.
Applying this change specifically to the `chefspec` unit test will
prevent the env var from affecting other tests.
I've verified this corrects the issue locally, but we'll hold on merging until  for the verification pipeline completes. 
Fixes #2754

Ensure we don't pull chef gem from git in chefspec

---

omnibus/Gemfile.lock
omnibus/config/software/ruby-windows-system-libraries.rb

This PR is in preparation for introducing MSYS_INSTALL_DIR environment variable in next release of omnibus-toolchain. We do not ship msys2 for windows in omnibus-toolchain anymore, so this variable sets the PATH where msys2 is installed on the AMI
Set msys2_path to the path defined by MSYS_INSTALL_DIR for Windows builds

Update Windows msys2_path to custom installed msys2 lookup first

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

This gem seems to cause failures for us since there's no 32bit version

Pin ruby-prof < 1.4 to avoid x64-mingw32 gem

---

Rakefile
lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

tk-policyfile-provisioner is undocumented and should be unused at this point.

Swap tk-policyfile-provisioner testing for a basic cookstyle test

---

.expeditor/verify.pipeline.yml
Gemfile
Gemfile.lock

This fixes the crashes on Windows nodes

Remove the pin on FFI now that 1.13.1 is out

---

README.md

This sets Issue and PR SLA to 'never', and updates status to
'Maintained'.  As a product, Chef DK has been deprecated. Because we're
still releasing security updates, gem version updates, and critical fixes
the repo status of 'maintained' is more correct than 'deprecated'.
Added a description blurb to direct people to the Workstation project
and downloads.

Update project status to 'maintained'

---

.expeditor/release.omnibus.yml

These are both EOL platforms now

Remove EOL Debian 8 / RHEL 8 packages
