lib/chef-dk/skeletons/code_generator/files/default/serverspec_spec_helper.rb
lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/serverspec_default_spec.rb.erb
spec/unit/command/generator_commands/app_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb

Not entirely sure how I broke it but somehow I deleted the branch out from under pull #268 when rebasing it. Will close that un-merged, and merge this one instead.

Add serverspec to cookbook & app generators

---

CHANGELOG.md
lib/chef-dk/version.rb

The changes for the omnibus package: https://github.com/opscode/omnibus-chef/pull/323
cc @opscode/client-engineers

chefdk 0.3.6

---

CHANGELOG.md
lib/chef-dk/version.rb

Any interest in doing this?
cc @danielsdeleo @lamont-granquist @sersut @charlesjohnson @chef/client-engineers

Bump version to 0.4.0

---

CHANGELOG.md

* These were added in 0.3.6 via #266

Add chefspec and serverspec to the CHANGELOG

---

README.md

- The mixed case of ChefDK doesn't work with brew cmd.

doc: explicit brew install.

---

Gemfile
lib/chef-dk/cli.rb
spec/unit/cli_spec.rb

Fixes https://github.com/chef/chef-dk/issues/48

Print versions of common tools when doing --version on chef-dk

---

lib/chef-dk/command/shell_init.rb
spec/unit/command/shell_init_spec.rb

/cc @smith @seth @jdmundrawala

Add Fish shell support to `chef shell-init`

---

CHANGELOG.md
lib/chef-dk/version.rb

\cc @jdmundrawala @danielsdeleo

Preping for 0.5.0 release with CHANGELOG updates and version file update

---

README.md

Update shell-init docs for posh and fish

---

lib/chef-dk/command/diff.rb
spec/unit/command/diff_spec.rb

Fixes fixes https://github.com/chef/chef-dk/issues/366
\cc @chef/client-core

Fixing undefined_method error

---

appveyor.yml
chef-dk.gemspec

Tried this on a few policyfiles and it worked fine.
It should help generate dependency solutions that are a bit more inline with what people expect.

Update to Solve 2 with Molinillo solver

---

chef-dk.gemspec
lib/chef-dk/version.rb

Testing out chef-provisioning 1.2 and knife-windows 1.0 RC

---

lib/chef-dk/command/verify.rb
lib/chef-dk/version.rb
spec/unit/command/verify_spec.rb

Fixes #420 
Moving this from 6-stable to master
\cc @fnichol @danielsdeleo @jdmundrawala

Adding verification for openssl Windows issue to prevent regression, fixes #420

---

lib/chef-dk/builtin_commands.rb
lib/chef-dk/command/env.rb
spec/unit/command/env_spec.rb

```yaml
---
Chef Development Kit:
ChefDK:
ChefDK Version: 0.7.0.rc.0
ChefDK Home: "/Users/jmundrawala/.chefdk"
ChefDK Install Directory: "/opt/chefdk"
Policyfile Config:
Cache Path: "/Users/jmundrawala/.chefdk/cache"
Storage Path: "/Users/jmundrawala/.chefdk/cache/cookbooks"
Ruby:
Ruby Executable: "/Users/jmundrawala/.rbenv/versions/2.1.2/bin/ruby"
Ruby Version: 2.1.2
RubyGems:
RubyGems Version: 2.4.4
RubyGems Platforms:
- ruby
- x86_64-darwin-13
Gem Environment:
GEM ROOT: "/Users/jmundrawala/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0"
GEM HOME: "/Users/jmundrawala/.gem/ruby/2.1.0"
GEM PATHS:
- "/Users/jmundrawala/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0"
- "/Users/jmundrawala/.gem/ruby/2.1.0"
Path:
- "/opt/chefdk"
- "/Users/jmundrawala/.gem/ruby/2.1.0/bin"
- "/opt/chefdk"
- …
```

Added chef env command

---

POLICYFILE_README.md

Adding policyfile usage instructions to POLICYFILE_README.md

---

README.md

\cc @chef/client-core 
I got tired of forgetting how to do this, so I'm adding documentation so that I can remember.

Adding pre-release install instructions

---

CHANGELOG.md
POLICYFILE_README.md

Adds a changelog entry for #450 and updates policyfile readme with info about `default_source` and cleans up some outdated info.

Policyfile doc updates

---

lib/chef-dk/skeletons/code_generator/files/default/chefignore

Ignore more commonly included files that shouldn't be stored on the server

Add additional files to the chefignore file

---

lib/chef-dk/command/shell_init.rb
lib/chef-dk/completions/bash.sh.erb
spec/unit/command/shell_init_spec.rb

Adds very basic completion for subcommand names for bash.

Add shell completion for bash

---

lib/chef-dk/command/verify.rb

- Run 'require' on all the provisioning gems
- Fail if there's more than one version of chef-provisioning or its drivers.

Corrective actions from 9/9/15 incident

---

lib/chef-dk/command/verify.rb
spec/unit/command/verify_spec.rb

https://github.com/chef/chef-dk/issues/538 needs to be fixed in the packaging, but this is a test that would have caught that issue.

Verify that the policyfile_zero provisioner can load

---

lib/chef-dk/command/generate.rb
lib/chef-dk/command/generator_commands/generator_generator.rb
spec/spec_helper.rb
spec/unit/chef_runner_spec.rb
spec/unit/command/generator_commands/generator_generator_spec.rb

The goal is to reduce the barrier to using a custom generator so users who have different opinions than the default generator can have a good experience.

Generate generator

---

lib/kitchen/provisioner/policyfile_zero.rb

Fixes an issue where the presence of a Berksfile makes TK try to load
berkshelf (which we don't want anyway) which then has a dependency
conflict with ChefDK.
This is a bit ugly b/c Kitchen is halfway between a composition and inheritance based approach to code reuse; this is the least monkey-patchy I could do it. 
I think the long-term correct fix is 1) chef-zero supports policyfile native mode, 2) chef-client pulls in this version of chef-zero, 3) `chef export` can export policy dirs in the format chef-zero likes, then 4) move the policyfile provisioner (or just the relevant parts) into TK, and auto-activate it if there's a Policyfile, but this prevents us from triggering a confusing error in the meantime.

Further customize kitchen to avoid berksfile detection

---

lib/chef-dk/skeletons/code_generator/recipes/app.rb
lib/chef-dk/skeletons/code_generator/recipes/repo.rb

take two, using internals as suggested in #553

add git init condition to prevent init inside an existing git repository

---

POLICYFILE_README.md

* remove implemented features from "known limitations" section
* tone down language about the feature being experimental
* clarify the status of role support
* fix a bunch of typos
/cc @adamedx

Update POLICYFILE_README for the current state of the world

---

lib/chef-dk/command/verify.rb
lib/chef-dk/component_test.rb
lib/chef-dk/exceptions.rb

/cc @danielsdeleo @schisamo @jkeiser

Update chef verify to pull component tests from gems

---

lib/chef-dk/policyfile_compiler.rb
spec/unit/policyfile_demands_spec.rb

In the original implementation of multiple default sources, I took the most conservative possible route, making it an error condition if any cookbooks appeared in more than one of the sources and didn't have a `cookbook "name", explicit_source_option` statement. The problem with this approach is that even if a cookbook could never be in or affect the dependency solve, you had to make a `cookbook` statement for it, which has the side-effect of pulling the cookbook into the solution even if you don't want it. Also, it's just annoying and isn't protecting the user from anything--the cookbook wouldn't be used if we had just ignored the conflict.
This patch adds a simple graph traversal function which finds all cookbooks that could possibly be in the dependency solve. If any conflict is …

Only report cookbook source conflicts that could affect solution

---

lib/chef-dk/command/verify.rb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/verify_spec.rb

\cc @jkeiser @danielsdeleo @randomcamel @adamedx

Adding `chef verify inspec` and Test Kitchen verifier to generators (commented out)

---

lib/chef-dk/chef_runner.rb
spec/unit/chef_runner_spec.rb

Fixes https://github.com/chef/chef-dk/issues/594
cc @jtimberman @chef/workflow

Forcibly unset policyfile config in embedded chef runs

---

lib/chef-dk/policyfile/dsl.rb
spec/unit/policyfile_evaluation_spec.rb

Based on Chef Server's validation as done here:
https://github.com/chef/chef-server/blob/015cf2546d67c3b4ded3c88c9d6db13ab3d78093/src/oc_erchef/apps/chef_objects/src/chef_regex.erl#L61
/cc @chef/workflow

Sanity check run list item format

---

omnibus/Gemfile.lock
omnibus/files/mapfiles/solaris

@scotthain @schisamo 
/cc @chef/engineering-services

Bump omnibus and update solaris mapfile

---

lib/chef-dk/skeletons/code_generator/files/default/repo/policies/README.md

Fixed typo in repo README

---

omnibus/Gemfile.lock
omnibus/config/projects/chefdk.rb

This change pulls in openssl 1.0.1r

Pull in latest omnibus and omnibus-software

---

omnibus/config/projects/chefdk.rb

bump to latest released versions

synch bundler+rubygems with chef/chef

---

omnibus/resources/chefdk/msi/localization-en-us.wxl.erb

Make same change for chefdk as we did for chef client (https://github.com/chef/chef/pull/4551)
@chef/client-core @jaym @btm

Update ManufacturerName to be a cleaner string

---

omnibus/resources/chefdk/msi/assets/start-chefdk.ps1
omnibus/resources/chefdk/msi/source.wxs.erb

This takes a different approach from #677 and simply elevates the new processes and drops the icons.

elevate windows shortcuts

---

lib/chef-dk/builtin_commands.rb

Fix typo in builtin_commands.rb

---

RELEASE_NOTES.md

Release notes for ChefDK 0.11.0

Update release notes for 0.11

---

omnibus/Gemfile

Fix an accidental change to omnibus-software pin.
@chef/omnibus-maintainers @jaym @jkeiser

Fix omnibus software pin

---

omnibus/config/projects/chefdk.rb

Updating pins for inspec and kitchen-inspec to more recent ones 
@jaym

Try more recent pins

---

lib/chef-dk/version.rb

Bump up the chef-dk version to 0.11.2 
@chef/client-core

Bump version to 0.11.2

---

chef-dk.gemspec

Work around broken github-changelog-generator

---

POLICYFILE_README.md

also tone down the warnings a bit more

Update POLICYFILE README for chef-client 12.7 release

---

Gemfile

Mitigates the impact of a packaging issue.

Install chef 12.8.1 from tag for now

---

ci/verify-chefdk.sh

Rebased https://github.com/chef/chef-dk/pull/730 and left just the change to add acceptance.
Running http://manhattan.ci.chef.co/job/chefdk-build/78/downstreambuildview/ to see if I can repro the prior issues with the build script.

have acceptance jenkins matrix entry run chef-acceptance

---

omnibus/config/projects/chefdk.rb
omnibus/config/software/chefdk-env-customization.rb
omnibus/config/software/chefdk.rb
omnibus/config/software/rubygems-customization.rb

Add licensing metadata for chefdk project
@chef/engineering-services @sersut`

add omnibus licensing metadata

---

omnibus/Gemfile
omnibus/Gemfile.lock

Because https://github.com/chef/omnibus/pull/661 was merged
\cc @randomcamel @chefsalim @mwrock @jkeiser

Removing json from the Omnibus Gemfile because we worked around the bug

---

tasks/bin/bundle-platform.bat

adds a bin stub for running rake dependencies on windows

---

Gemfile

We made this change to the chef Gemfile but neglected to make it here.

Fix Gemfile on windows

---

README.md
RELEASE_NOTES.md

Adds the text we discussed in chat to RELEASE_NOTES.
The README changes are just formatting the lines to 80 chars like the rest of the README (this doesn't add newlines, you need two newlines to make a `<br />`).

Cookstyle docs note

---

lib/chef-dk/command/verify.rb
lib/chef-dk/component_test.rb
omnibus/Gemfile.lock
omnibus/config/software/chef-dk-complete.rb

[Passing build](http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/258/downstreambuildview/)

Include git on windows.

---

spec/unit/command/base_spec.rb

But it looks like the test should have been failing anyways
\cc @tylercloke @thommay @sersut 
Travis failure on master: https://travis-ci.org/chef/chef-dk/builds/128080301

This mixlib-cli 1.5.0 -> 1.6.0 started making 2 of our tests fail

---

omnibus/config/software/chef-dk-complete.rb

merge after https://github.com/chef/omnibus-software/pull/663 is merged

Updating chef-dk-complete to include permission fix for gems from omnibus-software

---

omnibus/config/software/chef-dk-complete.rb

\cc @mwrock @randomcamel @PrajaktaPurohit @jkeiser 
I already sent an ad-hoc build through and it was successful

Building git early in the omnibus pipeline so we can take advantage of cacheing for it

---

CONTRIBUTING.md

CONTRIBUTING update to reflect Discourse mailing list

---

ci/verify-chefdk.sh

See individual commit messages for full details. Same change as https://github.com/chef/chef/pull/4917
/cc @chef/engineering-services @ksubrama @tyler-ball

relocate chef-acceptance data output to Jenkins workspace

---

ci/verify-chefdk.sh

We output all data generated during a chef-acceptance run to the workspace of the executing Jenkins job using chef-acceptance's `--data-path` option. If the `chef-acceptance` commands are executed with elevated privileges (using `sudo`) the generated files are owned by `root`:
https://gist.github.com/schisamo/7ce7262813f2bc81b7314d9eab53afa0
This is an issue as the generated data cannot be properly archived OR cleaned up when the next job runs:
https://gist.github.com/schisamo/b7246987d49534b27b8a4ad72f9ad965
/cc @chef/engineering-services 
This is a similar fix that was applied to Chef in: https://github.com/chef/chef/pull/4932

Execute chef-acceptance without elevated privileges

---

Gemfile.lock
lib/chef-dk/version.rb

http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/304/downstreambuildview/
manually update version in lib/chef-dk/version.rb
bundle install rake bundle:install

Updating the version to 0.15 after release

---

omnibus/config/software/chef-dk-appbundle.rb
omnibus/config/software/chef-dk-gem-ffi.rb
omnibus/config/software/chef-dk-gem-ruby-prof.rb
omnibus/config/software/chef-dk-gem-ruby-shadow.rb

http://manhattan.ci.chef.co/job/chefdk-build/474/

Fix auto dependency bumps, include appropriate license information where necessary

---

omnibus/Gemfile.lock

TODO:
[Build](http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/350/downstreambuildview/)

Delivery CLI 1.8.0 compatibility

---

lib/chef-dk/command/generator_commands/cookbook.rb
spec/unit/command/generator_commands/cookbook_spec.rb

When there is a `.delivery/cli.toml` upwards from the current working directory, `chef generate cookbook` tells users to run `delivery init` to create their pipeline.

Emit a delivery-specific breadcrumb when appropriate

---

lib/chef-dk/skeletons/code_generator/files/default/build-cookbook/.kitchen.yml
lib/chef-dk/skeletons/code_generator/files/default/build-cookbook/README.md
lib/chef-dk/skeletons/code_generator/files/default/repo/README.md
lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/README.md
lib/chef-dk/skeletons/code_generator/files/default/repo/data_bags/README.md

Minor updates broken out per commit

Generator readme updates

---

Gemfile
Gemfile.lock

This is basically the same change I made in chef/chef, but with the wording changed slightly. Should allow for better bug reports

Ship kitchen-dokken in ChefDK

---

Gemfile.lock
chef-dk.gemspec
version_policy.rb

See https://github.com/chef/mixlib-cli/issues/29. This could break some knife scenarios until mixlib-cli is fixed.

pin mixlib-cli

---

lib/chef-dk/skeletons/code_generator/recipes/cookbook_file.rb

Found a place that interpolation wasn't needed. Quick fix :metal:

No need for interpolation here

---

lib/chef-dk/command/clean_policy_cookbooks.rb
lib/chef-dk/command/clean_policy_revisions.rb
lib/chef-dk/command/delete_policy.rb
lib/chef-dk/command/delete_policy_group.rb
lib/chef-dk/command/export.rb
lib/chef-dk/command/install.rb
lib/chef-dk/command/push.rb
lib/chef-dk/command/push_archive.rb
lib/chef-dk/command/show_policy.rb
lib/chef-dk/command/undelete.rb
lib/chef-dk/command/update.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/cookbooks/example/recipes/default.rb
lib/chef-dk/skeletons/code_generator/files/default/repo/data_bags/README.md
lib/chef-dk/skeletons/code_generator/files/default/repo/roles/README.md
lib/chef-dk/skeletons/code_generator/templates/default/Policyfile.rb.erb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/policyfile_spec.rb
spec/unit/command/generator_commands/repo_spec.rb

The github link just links to the docs anyways

Link to the policy file docs not Github

---

Gemfile.lock
acceptance/Gemfile.lock
omnibus/Gemfile.lock

Bump deps to the latest

---

tasks/bundle.rb

Copy over the same fixes from https://github.com/chef/chef/pull/5162

---

version_policy.rb

Signed-off-by: Matt Wrock <matt@mattwrock.com>

small change to test bump bot

---

Gemfile
Gemfile.lock

Wanted to make sure we get knife-windows 1.7.0 and this also includes the just released chef client along with a few other goodies.

update chef client and deps

---

omnibus/Gemfile
omnibus/Gemfile.lock

Pull in the latest omnibus and omnibus-software (specifically for Rust
1.12 for delivery-cli)

Update omnibus deps

---

CHANGELOG.md

Update changelog for 0.19.6 release.
/cc @mwrock @charlesjohnson @tduffield @afiune

Update changelog for 0.19.6 release.

---

RELEASE_NOTES.md

Please update the Release Notes with any additional relevant information by committing the changes to this branch.
/cc @coderanger @mwrock @charlesjohnson @tduffield

Update Release Notes for 0.19 Release

---

Gemfile.lock
lib/chef-dk/version.rb

Bump to 0.20

---

Gemfile.lock

This bumps our testing deps so we can get the latest and greatest out to the public

Bump deps for latest fauxhai/chefspec/inspec

---

omnibus/config/software/chef-dk-appbundle.rb

This ensures code introduced in #1071 works as expected
/cc @chef/client-core

Appbundle InSpec

---

CHANGELOG.md
HISTORY.md
RELEASE_NOTES.md
tasks/github_changelog_generator.rb

* Update the changelog generator 
* Update the docs for the 1.0 release

Update docs for 1.0 Release

---

.bundle/config
Gemfile.lock
RELEASE_NOTES.md
lib/chef-dk/version.rb

With the release of 1.0, bump version to 1.1

Bump to 1.1.0

---

lib/chef-dk/skeletons/code_generator/templates/default/inspec_default_test.rb.erb

Link to the inspec resources page

---

Gemfile
Gemfile.lock
HISTORY.md
chef-dk.gemspec
ci/version_bump.sh
tasks/github_changelog_generator.rb

Much like we are doing for Chef, let's update the CHANGELOG every time we merge a PR and update the version.

Update CHANGELOG on every PR merge

---

Gemfile
Gemfile.lock

Bring in the latest released chef-client

Include Chef 12.17.44

---

Gemfile.lock

Update dependencies to trigger build

Update cookstyle and knife-spork to the latest versions

---

ci/version_bump.sh

I can't believe this.  Wasn't me! 😭 

Fix weird char

---

RELEASE_NOTES.md

Update Release Notes for v1.1

---

RELEASE_NOTES.md
lib/chef-dk/skeletons/code_generator/files/default/delivery-project.toml
spec/unit/command/generator_commands/cookbook_spec.rb

Add new options that we just added to the delivery-cli to the `project.toml` generator.

Add new options to project.toml generator

---

Gemfile.lock
acceptance/Gemfile
acceptance/Gemfile.lock
omnibus/Gemfile.lock

Pin rainbow gem to address sickill/rainbow#44 and unblock acceptance tests.

Pin rainbow to address gem conflict errors in acceptance tests

---

RELEASE_NOTES.md

This PR needed to be documented in the release notes since it has customer impact.
https://github.com/chef/chef-dk/pull/1077

Adding missing release notes

---

RELEASE_NOTES.md

Update release notes for 1.2 release

---

RELEASE_NOTES.md

Specify FIPS support is for Windows and RHEL only in Release Notes

---

HISTORY.md

Update HISTORY.md post 1.2 release

---

tasks/version.rb

Archive the CHANGELOG to HISTORY when we bump major/minor versions

---

omnibus/Gemfile.lock

Confirmed via ad-hoc builds 
* Failing Builds

Update omnibus-software to pull in openssl patch fixes

---

omnibus/package-scripts/chefdk/postinst
omnibus/package-scripts/chefdk/postrm

Cleanup the symlinks we create / remove on binary install

---

RELEASE_NOTES.md

Update RELEASE NOTES

---

Gemfile
Gemfile.lock

Remove veil gem

---

RELEASE_NOTES.md

Update Chefspec release notes

---

RELEASE_NOTES.md

Consistent wording and link to the dokken changelog

More release notes updates for the next release

---

lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/README.md
lib/chef-dk/skeletons/code_generator/templates/default/recipe_spec.rb.erb

Avoid deprecation warnings and outright failures

Generate better example ChefSpec code

---

README.md

* Add release policy to the README

Add release policy to README

---

omnibus/Gemfile
omnibus/Gemfile.lock

Let us all celebrate and rejoice!

Point omnibus and omnibus-software at master branches

---

lib/chef-dk/skeletons/code_generator/files/default/build_cookbook/.kitchen.yml
lib/chef-dk/skeletons/code_generator/templates/default/kitchen.yml.erb
lib/chef-dk/skeletons/code_generator/templates/default/kitchen_policyfile.yml.erb
omnibus/.kitchen.yml
spec/unit/command/generator_commands/cookbook_spec.rb

Use CentOS 7.3 in the Test Kitchen configs

---

lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb
lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb

Signed-off-by: Nathen Harvey <nharvey@chef.io>

Write proper SPDX License strings

---

RELEASE_NOTES.md

Update release notes with FIPS warning

Update release notes with FIPS warning

---

RELEASE_NOTES.md

Note the changes to chef generate cookbook

---

omnibus/Gemfile.lock

Fixes our OpenSSL installation for FIPS Windows customers. See https://github.com/chef/omnibus-software/pull/823 for details.
N/A

Pulling OpenSSL FIPS fixes from https://github.com/chef/omnibus-software/pull/823

---

Gemfile.lock

Cleans up the build pipeline so I can get the FIPS patch release out
N/A

Fixing dependencies to fix the build pipeline

---

README.md

Fix a bad link to caskroom

---

README.md

We have a nice doc that explains it now. Lets link it

Add cookstyle to the list of utilities in DK

---

ci/dependency_update.sh
ci/version_bump.sh

.bundle/config is no longer in git

---

Gemfile
Gemfile.lock
tasks/github_changelog_generator.rb

use correct changelog generator

---

lib/chef-dk/skeletons/code_generator/recipes/template.rb

Create a Chef 12 style templates dir instead of a Chef 11 style dir

---

Gemfile
Gemfile.lock
RELEASE_NOTES.md
lib/chef-dk/version.rb

Remove poise boiler

---

lib/chef-dk/chef_runner.rb

Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>

updated the error message for proper clarification of error message

---

Gemfile
Gemfile.lock

try pinning cookstyle

---

lib/chef-dk/skeletons/code_generator/templates/default/metadata.rb.erb

Fix typo in metadata.rb.erb template file

---

.expeditor/update_version.sh

Simple tweak to unblock our version bumping pipeline.

Don't attempt to checkout .bundle/config

---

lib/chef-dk/skeletons/code_generator/recipes/build_cookbook.rb

Not all platforms (looking at you Windows) have a grep binary. Instead, let's do a simple regex.
This is an alternative implementation of #1054 (thanks for catching this @derekgroh)
* Closes 1054

Cross-platform modified files detection

---

omnibus/Gemfile.lock

since i just force pushed it, we're gonna be red without this.

update the omnibus dep on my branch

---

Gemfile
Gemfile.lock

Use the chef 13.2 release

---

RELEASE_NOTES.md

Update release notes for 2.0

---

Gemfile.lock

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

bump gemfile.lock

---

Gemfile
Gemfile.lock

i have no idea where the issue is that tracks this, but its definitely very broken

temporarily pin molinillo until it is un-busted

---

omnibus/Gemfile.lock
omnibus/config/software/git-custom-bindir.rb

bump git to 2.14.1 (CVE-2017-1000117)

---

lib/chef-dk/skeletons/code_generator/files/default/gitignore

It is now-recommended replacement for Gemfile.lock

Add gems.locked in .gitignore

---

.expeditor/config.yml
.github/CODEOWNERS
CHANGELOG.md

Update the Expeditor configuration to match 0.5.0 requirements. 
For more info, you can see the new docs site: http://expeditor-docs.es.chef.io

Update Expeditor config to meet 0.5.0 requirements

---

.expeditor/config.yml

Update ChefDK 1 branch to Expeditor 0.5.0 syntax

---

Gemfile
Gemfile.lock

Mitigate test-kitchen/test-kitchen#1277, chef/chef#6433 and friends

lock net-ssh to 4.1.0

---

CONTRIBUTING.md

Document how expeditor interacts with ChefDK, how the dependency update process works, and some misc fixes.

fix the development docs and place them correctly

---

.travis.yml

Test on Ruby 2.4.2

---

Gemfile
Gemfile.lock
acceptance/Gemfile.lock
omnibus/Gemfile.lock

This is the latest release of Chef, which has behavior changes in
scheduled_task vs. 13.4.19

Ship Chef 13.4.24 in DK

---

.expeditor/config.yml

[Expeditor] Use new glob-style version matching

---

README.md

…NG.md` to reflect filename changes introduced in commit `6e87d1d424bf04f277331bfe9a1b457c882092aa`
Signed-off-by: Robert Miesen <robert.miesen@gmail.com>
In commit `6e87d1d424bf04f277331bfe9a1b457c882092aa`, the `DEVELOPMENT.md` file was renamed to `CONTRIBUTING.md`. However, the `README.md` file still pointed to the now non-existent `DEVELOPMENT.md` file. This change fixes that.
None.

Changed "Development Guide" link target from DEVELOPMENT.md to CONTRIBUTING.md

---

Gemfile.lock
acceptance/Gemfile.lock
omnibus/Gemfile.lock

Update Test Kitchen to 1.19

---

appveyor.yml

Fix a minor typo in the appveyor config

Fix echo typo in appveyor

---

Gemfile
Gemfile.lock
acceptance/Gemfile.lock
omnibus/Gemfile.lock

Pull in Chef 13.6.4, knife-ec2 0.16 and fauxhai 5.5

---

Rakefile

Enable FC011 testing for the skeleton cookbook

---

.travis.yml

Test on Ruby 2.4.3

---

appveyor.yml

This resolves a lot of the random failures we were seeing in chef/chef

Test on the latest Appveyor boxes

---

Gemfile
Gemfile.lock
RELEASE_NOTES.md

Pull in Chef 13.8.5 and knife-windows 1.9.1

---

lib/chef-dk/skeletons/code_generator/files/default/cookbook_readmes/README.md

Remove the reference to the community site from the generated cookbooks readme

Format cookbooks generated readme & reference supermarket

---

RELEASE_NOTES.md

Signed-off-by: Scott Hain <shain@chef.io>

Deprecate OSX 10.10 builds

---

Dockerfile

- Added git as a tool for helping pull down cookbooks and gems from source.
Signed-off-by: JJ Asghar <jj@chef.io>

Added git for the build container

---

.travis.yml
chef-dk.gemspec
spec/unit/policyfile_evaluation_spec.rb

bump travis, bump ruby, fix a spec

---

.travis.yml
Gemfile
Gemfile.lock
appveyor.yml
omnibus/config/software/chef-dk.rb

These will soon become dependencies of berks and policyfiles

Ship libarchive and ffi-libarchive

---

Gemfile
Gemfile.lock

companion piece to chef/chef#7191

 pin ffi to avoid el6/el7 bugginess

---

.expeditor/config.yml

same as chef/chef#7190
(i keep on fixing bugs in chef-dk and seeing the same failures in chefdk-test that i know i just fixed)

expeditor force expire cache

---

.expeditor/config.yml

that didn't help any, something else has gone wrong here.

remove expire cache

---

Gemfile.lock

pulls in https://github.com/chef/appbundler/pull/43

bump appbundler dep to rebuild

---

RELEASE_NOTES.md

ensure git targets are in the rel notes

---

omnibus/resources/chefdk/msi/source.wxs.erb

This is an update to the Support/Help URL that is exposed in Add/Remove Programs on Windows.

Update help link in Add/Remove Programs on Windows

---

Gemfile.lock
omnibus/Gemfile.lock

Pull in the latest tools

---

.expeditor/config.yml

We don't have any of these labels on this project and we're not building DK 1 again

Expeditor: Remove DK1 and old labels

---

omnibus_overrides.rb

This matches the update we made in DK 3

Update libxml2 to 2.9.8

---

.expeditor/config.yml
CHANGELOG.md

Add missing changelog entries and update expeditor config

---

Gemfile.lock

No major version bumps here. Just some solid bugfixes.

Bump to latest test-kitchen, kitchen-digitalocean, kitchen-ec2, and knife-ec2

---

.expeditor/config.yml

We're using this in a lot of our other projects

Add version bumping / PR branch deletion to expeditor config

---

.expeditor/config.yml

Remove deprecated maintainer_group config in expeditor

---

Gemfile.lock

Updating dependencies to pull in latest chef-apply release

---

.expeditor/update_dep.sh

Exported functions (like open_pull_request) only work in Bash.
Manually tested this and it found the new function

Need to run expeditor scripts in Bash not Posix Shell

---

.expeditor/update_dep.sh

So the DCO bot isn't so 😭 
N/A

Sign off on dependency updating PRs

---

Dockerfile

Switch docker container to Ubuntu 18.04 and fix Ruby path

---

RELEASE_NOTES.md
lib/chef-dk/command/verify.rb

Also uncommenting the chef tests since we're now pulling in Chef 14.4

Preparing release notes for 3.2 release

---

omnibus/Gemfile.lock

This includes a good number of bug fixes and is available in the omnibus-software repository now.

Update libarchive to 3.3.3

---

Gemfile.lock
omnibus/Gemfile.lock

Update chefspec to 7.3.2

---

omnibus/Gemfile.lock

Latest omnibus-software
Chef 14.5

Update omnibus build deps to the latest

---

lib/chef-dk/command/generate.rb

Add deprecation warnings to the help and prints a warning when they're used.
```
❰tsmith❙~/dev/work/chef-dk(git✱generate_13)❱✘≻ bin/chef generate app bob                                        11:56:45
WARNING: The command 'chef generator app' is deprecated and will be removed from the next major release of Chef DK / Workstation (April 2019)
Recipe: code_generator::app
* directory[/Users/tsmith/dev/work/chef-dk/bob] action create
- create new directory /Users/tsmith/dev/work/chef-dk/bob
* template[/Users/tsmith/dev/work/chef-dk/bob/.kitchen.yml] action create
- create new file /Users/tsmith/dev/work/chef-dk/bob/.kitchen.yml
- update content in file /Users/tsmith/dev/work/chef-dk/bob/.kitchen.yml from none to bd2df3
(diff output suppressed by config)
* …
```

Add a deprecation warning for chef generate app / lwrp

---

RELEASE_NOTES.md

Preparing ChefDK 2 for release
N/A
- ~New functionality includes tests~
- ~All tests pass~

Preparing 2.6 release notes

---

RELEASE_NOTES.md

Starts a section to collect release-worthy but not-yet-released notes therein.
Also ficks sum grammerz in a note for 3.3.
* a home for notes for a pending release
* bad grammar
- ~New functionality includes tests~
- ~All tests pass~

start section to collect notes for yet-to-be-released changes

---

omnibus/config/projects/chefdk.rb

We've been doing this in chef-client for a while.

Enable deb/rpm compression

---

Gemfile.lock

Manually updating dependencies b/c there was an Expeditor outtage earlier

---

.expeditor/config.yml

- ~[ ] New functionality includes tests~
- ~[ ] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)~

Fix chef-apply subscription

---

.github/CODEOWNERS

☝️ 
- ~[ ] New functionality includes tests~
- ~[ ] All tests pass~
- ~[ ] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)~

Add Workstation team to CODEOWNERS

---

.expeditor/config.yml

This has been really useful for reducing maint burden

Add more gem release subscriptions

---

RELEASE_NOTES.md

☝️ 
N/A
- ~[ ] New functionality includes tests~
- ~[ ] All tests pass~

Preparing 3.4 release notes

---

RELEASE_NOTES.md

Bumping ChefDK minor version after 3.4 release

---

.expeditor/config.yml

Workstation owns ChefDK, so let those humans know what's up.

send pipeline notifications to the Workstation team channel

---

RELEASE_NOTES.md

Some notes about the release, yo.
... The lack of release notes? Note to selves: we need to get better at including that "RELEASE\_NOTES.md has been updated" item from the PR check list during review.
-  ~New functionality includes tests~

update release notes for 3.5

---

.travis.yml
appveyor.yml

We were excluding groups we no longer have

Update the groups to exclude in appveyor and travis

---

Rakefile
chef-dk.gemspec

These only ever need to get run from the source. Rescue the failure if
they can't be found.

Don't ship the rake tasks in the gem artifact

---

omnibus_overrides.rb

Porting https://github.com/chef/chef/pull/8091 to the DK
N/A

Update rubygems to 2.7.7 and bundler to 1.17.3

---

Gemfile.lock
appveyor.yml

Need to install Bundler 2.0 until they make 1.x compatible with 2.x written lock files

---

RELEASE_NOTES.md

Add a note about the deprecation in #1925
Signed-off-by: Bryan McLellan <btm@loftninjas.org>

Start ChefDK 3.7 release notes

---

Gemfile.lock

Pin bundler back to 1.17.3.

---

.expeditor/config.yml

Fixing our expeditor labels to match pre-generated ones in Github

---

omnibus_overrides.rb

Upgrade rubygems to 2.7.8

---

RELEASE_NOTES.md

Preparing release notes for 3.7 release

---

RELEASE_NOTES.md

Bumping to 3.8 for new minor version development.

---

Gemfile
Gemfile.lock

add ed25519 gemset

---

RELEASE_NOTES.md

Preparing for 3.8 release.

---

.travis.yml

Test on the xenial boxes in Travis

---

.expeditor/update_chef.sh
.expeditor/update_dep.sh
.expeditor/update_dockerfile.sh

Expeditor now adds the EXPEDITOR_ prefix to help make it clearer which environment variables are included by Expeditor.

Add EXPEDITOR_ prefix to environment variables

---

Gemfile
Gemfile.lock

Rollback the addition of ed25519 support gems

---

.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md

This way we get a template for feature requests and one for bug reports.

Add individual Github templates

---

.expeditor/config.yml
.expeditor/update_dep.sh
.travis.yml
appveyor.yml

Make sure CI systems will test this new branch
Make sure expeditor knows about its version constraint
Make sure expeditor can bump the major version
Make sure expeditor opens PRs against the correct branch

Prepare DK to branch chefdk-3 as the stable branch

---

Gemfile
Gemfile.lock
lib/chef-dk/policyfile/dsl.rb
lib/chef-dk/policyfile/solution_dependencies.rb
lib/chef-dk/policyfile_lock.rb

This also allows us to test with the latest chefstyle, which alerted on a few new things.

Update to the latest major releases of Cookstyle / Fauxhai

---

omnibus_overrides.rb

This matches the version we'll use in Chef 15.

Update rubygems to 3.0.2

---

Gemfile
Gemfile.lock
chef-dk.gemspec

Grab Chef 15 from master (ohai/push jobs as well) so we can start testing this whole thing together as one.

Pull in Chef 15 from git

---

lib/chef-dk/skeletons/code_generator/files/default/chefignore

Sort the entries
Add .circleci
Add .github
Add azure-pipelines.yml

Update chef generate cookbooks chefignore file

---

appveyor.yml

Test on Ruby 2.6 in appveyor

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Bundler was hanging trying to dep solve. I added some constraints to simplify the set of deps.
Signed-off-by: Tim Smith <tsmith@chef.io>1

Pin inspec and other gems to prevent bundler hanging

---

.expeditor/update_dep.sh
Gemfile.lock
tasks/dependencies.rb

Pull in the new kitchen-ec2 and fauxhai releases

Fix expeditor updating + bump gem deps

---

Gemfile.lock
omnibus/Gemfile.lock

Nothing should impact DK here, but we might as well pull in the latest release.

Update mixlib-install to 3.11.18

---

.expeditor/config.yml

These don't work on the N-1 branch

Disable expeditor update subscriptions

---

RELEASE_NOTES.md

Release notes for 3.10

---

RELEASE_NOTES.md

Fixing formatting on release notes.

---

RELEASE_NOTES.md

Pull chefdk 3.9 and 3.10 release notes to master.

---

ci/verify-chefdk.bat
ci/verify-chefdk.sh

To fix failures in Manhattan
N/A

Accept the Chef EULA for CI pipeline testing

---

ci/verify-chefdk.sh

licence acceptance was in the wrong block, acceptance tests
were removed a long time ago.

Accept the license in CI and remove old acceptance tests

---

ci/verify-chefdk.sh

I should publish a newsletter about how much I hate sudo.

CI: avoid sudo env variable cleaning?

---

ci/verify-chefdk.bat

Accept the DK license during testing with the CLI flags

---

RELEASE_NOTES.md

Copyediting for ChefDK 4.0 release notes, which are WIP.

Copyediting for ChefDK 4.0 release notes

---

lib/chef-dk/command/verify.rb

StackOverflow discussions that are relevant]

Use bin chef-apply in testing

---

Gemfile.lock

Update license-acceptance gem to handle users specifying mixlib version as a channel

---

RELEASE_NOTES.md

☝️ Adding info we missed but found when creating https://discourse.chef.io/t/chefdk-4-0-released/15242
N/A

Adding EULA to the release notes for 4.0

---

Dockerfile

Add the proper ruby path to the Dockerfile

---

omnibus/package-scripts/chefdk/postinst

Help folks getting started a bit.

Direct folks to Learn Chef post install

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml

Allows us to move testing into BK

Add skeleton BK config

---

omnibus/config/software/chef-dk.rb

Chef depends on this now so we need to ship it.

Ship libarchive in the omnibus builds for chef

---

omnibus/omnibus-test.ps1
omnibus/omnibus-test.sh

This just updates the `omnibus-test.*` scripts to use tools that have been moved into the omnibus-toolchain. It also makes some changes to output to be more consistent across our omnibus projects.

[master] Use new omnibus-toolchain scripts in omnibus-test.* scripts

---

omnibus_overrides.rb

Update rubygems to 3.0.4

---

lib/chef-dk/command/shell_init.rb
lib/chef-dk/policyfile_services/push_archive.rb
spec/unit/policyfile_services/push_archive_spec.rb

This will help us release workstation with better help / error messages

Use the product constant in a few more places

---

omnibus/Gemfile.lock

Update curl to 7.65.1 to resolve a CVE

---

.expeditor/config.yml
Gemfile.lock

Also add an expeditor subscription so PRs will auto open in the future

Bump cookbook-omnifetch to 0.9.0

---

omnibus/package-scripts/chefdk/postinst
omnibus/package-scripts/chefdk/postrm

These are the same changes we're already running in Workstation

Remove smartos support from the install scripts

---

Gemfile.lock
omnibus/Gemfile.lock

Update knife-vsphere to 3.0.1

---

.expeditor/release.omnibus.yml

Enable RHEL 8 packages

---

omnibus/config/software/chef-dk.rb

We're doing this same thing in other projects

Concurrently install gems in the omnibus def

---

RELEASE_NOTES.md

Signed-off-by: Mary Jinglewski <mjinglewski@chef.io>
Fixing minor typo fixes so that release notes in both the repo and docs.chef.io are the same per https://github.com/chef/chef-web-docs/pull/2056

Minor typo fixes

---

RELEASE_NOTES.md

Some of this was lifted directly from the Chef Infra Client 15.2 release notes so it's already been checked over by docs.

Add DK 4.3 release notes

---

habitat/plan.sh

This matches the Omnibus definition of appbundling, which has been
working.
Fixes https://github.com/chef/chef-dk/issues/2246

Fix hab plan by appbundling without required deps

---

.expeditor/config.yml
Gemfile
Gemfile.lock
lib/chef-dk/command/verify.rb
omnibus/Gemfile.lock
spec/unit/command/verify_spec.rb

Updating gems to non-yanked versions

---

.expeditor/buildkite/verify.ps1
.expeditor/verify.pipeline.yml
spec/unit/command/generator_commands/build_cookbook_spec.rb
spec/unit/command/generator_commands/cookbook_spec.rb
spec/unit/command/generator_commands/generator_generator_spec.rb
spec/unit/command/generator_commands/repo_spec.rb
spec/unit/policyfile_services/export_repo_spec.rb

Add Buildkite windows verification

---

habitat/plan.sh

We have not been running Habitat builds for a while so we must have
missed a change to 'do_download'. Copying the pattern from Chef Infra
Client habitat package.
N/A

Fix Habitat build failure

---

.expeditor/verify.pipeline.yml

Test on buster containers not stretch containers

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
.gitignore

Cache bundled gems in s3 to speed up testing

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Update Chef Infra Client to 15.4.45 and cookstyle to 5.8.1

---

.expeditor/config.yml

Enable Habitat package promotions

---

Gemfile
Gemfile.lock

Update Chef Infra Client to 14.14.29

---

RELEASE_NOTES.md

Add release notes for DK 3.12.10

---

.expeditor/run_linux_tests.sh

The InSpec team did some work to improve the initial script. This should
help speed up builds.

Pull in the updated buildkite test script from the InSpec project

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
habitat/plan.sh
habitat/scripts/ci_integration_tests.sh
habitat/tests.sh

We reworkked all the habitat build logic in DK 4 and that didn't get
backported to DK 3. Our hab builds are just failing every time.

Fix habitat builds by using the DK4 plan

---

Gemfile.lock

Update kitchen-google to 2.0.2

---

Gemfile.lock
omnibus/Gemfile.lock

Bump omnibus to the latest

---

.expeditor/update_dep.sh

Hopefully this makes this all more reliable

Update the update_dep script to not fail

---

Gemfile.lock
omnibus/Gemfile.lock

Update all deps to current

---

Gemfile.lock
omnibus/Gemfile.lock

Update ffi-libarchive to 1.0.0

---

.github/lock.yml
Gemfile.lock
omnibus/Gemfile.lock

Update mixlib-shellout to 3.0.9 + bump omnibus deps

---

.expeditor/config.yml
Gemfile.lock
omnibus/Gemfile.lock

Add update subscriptions for these as well

Update yard and artifactory deps

---

Gemfile.lock
omnibus/Gemfile.lock

Update kitchen-azurerm to 0.15.1

---

omnibus/config/software/more-ruby-cleanup.rb

Keep warning.txt which we need in the DK gem

---

RELEASE_NOTES.md

Add release notes for DK 4.7

---

RELEASE_NOTES.md

Add ChefDK 3.13 release notes

---

omnibus/config/software/more-ruby-cleanup.rb

This was causing issues with the verify command. That's something to
figure out another time. For now we need to get things in a shape we can
ship.

Don't remove rakefile/gemfiles in gems

---

omnibus/config/software/git-custom-bindir.rb

Bump git to 2.24.1

---

omnibus/config/software/git-custom-bindir.rb
omnibus/config/software/more-ruby-cleanup.rb

This was missed since omnibus-software has the same update

Actually bump git to 2.24.1

---

RELEASE_NOTES.md

Update release notes for 15.7

---

Gemfile.lock
RELEASE_NOTES.md

Update Cookstyle to 5.20

---

Gemfile.lock

This swaps logify for mixlib-log

Update to chef-api 0.10.5

---

Gemfile.lock
omnibus/Gemfile.lock

Bring in the latest kitchen drivers

Update Test Kichen, kitchen-ec2, and kitchen-hyperv

---

Gemfile.lock

Update knife-cloud to 3.0.4

---

RELEASE_NOTES.md

Add DK 4.8 release notes

---

.expeditor/config.yml

Disable habitat in expeditor

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml

We're not going to ship this hab package again.

Remove hab pipelines in Expeditor

---

habitat/plan.sh
omnibus/config/software/chef-dk.rb

Don't appbundler chef-apply

---

omnibus/config/projects/chefdk.rb
omnibus/config/software/chef-dk.rb
omnibus/config/software/git-custom-bindir.rb
omnibus/config/software/more-ruby-cleanup.rb
omnibus/config/software/ruby-windows-system-libraries.rb

Update git to 2.26.2 and bring in DK 4 omnibus updates

---

Gemfile.lock

Pin back mini_portile2

---

RELEASE_NOTES.md

Add ChefDK 3.14 release notes

---

lib/chef-dk/command/verify.rb

Remove the verify step for chef-run

---

spec/unit/command/verify_spec.rb

Remove another test reference to chef-apply

---

.expeditor/config.yml

With Chef DK-3 EOL we have deleted the Buildkite pipelines and this PR prevents them from being recreated.
Signed-off-by: Christopher A. Snapp csnapp@chef.io

Remove Buildkite Pipelines

---

RELEASE_NOTES.md

Add 4.9 release notes

---

README.md

Update DK3 readme to mark it deprecated.

Make DK3 status deprecated

---

.dependabot/config.yml
omnibus/Gemfile.lock

Remove dependabot config for dk-3 and bump omnibus

---

Gemfile.lock

Update knife-opcs to 0.4.6

---

RELEASE_NOTES.md

Add DK 4.10 release notes

---

RELEASE_NOTES.md

Add ChefDK 4.11 release notes

---

RELEASE_NOTES.md

Add 4.12 release notes

---

omnibus_overrides.rb

Update libffi and libiconv to the latest

---

omnibus_overrides.rb

Fix the FFI version string
